#!/usr/bin/env bash
# tests/test_share.sh — share.yml management tests
#
# Verifies share_init, share_refresh, share_validate, and the cco share
# CLI commands.

# ── share_init ────────────────────────────────────────────────────────

test_share_init_creates_share_yml() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"
    assert_file_exists "$CCO_USER_CONFIG_DIR/share.yml"
}

test_share_init_contains_packs_section() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"
    assert_file_contains "$CCO_USER_CONFIG_DIR/share.yml" "packs:"
}

test_share_init_contains_templates_section() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"
    assert_file_contains "$CCO_USER_CONFIG_DIR/share.yml" "templates:"
}

test_share_init_idempotent() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"

    # Modify share.yml
    printf '\n# USER_CANARY\n' >> "$CCO_USER_CONFIG_DIR/share.yml"

    # Second init should NOT overwrite
    run_cco init --lang "English"
    assert_file_contains "$CCO_USER_CONFIG_DIR/share.yml" "USER_CANARY"
}

# ── share_refresh ─────────────────────────────────────────────────────

test_share_refresh_lists_packs() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco pack create "alpha-pack"
    assert_file_contains "$CCO_USER_CONFIG_DIR/share.yml" "alpha-pack"
}

test_share_refresh_removes_deleted_pack() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco pack create "temp-pack"
    assert_file_contains "$CCO_USER_CONFIG_DIR/share.yml" "temp-pack"
    run_cco pack remove "temp-pack"
    assert_file_not_contains "$CCO_USER_CONFIG_DIR/share.yml" "temp-pack"
}

test_share_refresh_multiple_packs() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco pack create "pack-a"
    run_cco pack create "pack-b"
    assert_file_contains "$CCO_USER_CONFIG_DIR/share.yml" "pack-a"
    assert_file_contains "$CCO_USER_CONFIG_DIR/share.yml" "pack-b"
}

test_share_refresh_preserves_name_and_description() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"

    # Set repo name and description
    cat > "$CCO_USER_CONFIG_DIR/share.yml" <<'YAML'
# Auto-generated by cco
name: "my-config"
description: "My personal config"

packs: []

templates: []
YAML

    # Create a pack (triggers refresh)
    run_cco pack create "new-pack"

    # Name and description should survive
    assert_file_contains "$CCO_USER_CONFIG_DIR/share.yml" "my-config"
    assert_file_contains "$CCO_USER_CONFIG_DIR/share.yml" "My personal config"
}

test_share_refresh_includes_templates() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"

    # Create a template directory manually
    mkdir -p "$CCO_TEMPLATES_DIR/my-template"

    run_cco share refresh
    assert_file_contains "$CCO_USER_CONFIG_DIR/share.yml" "my-template"
}

test_share_refresh_empty_when_no_packs_or_templates() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"
    run_cco share refresh
    assert_file_contains "$CCO_USER_CONFIG_DIR/share.yml" "packs: []"
    assert_file_contains "$CCO_USER_CONFIG_DIR/share.yml" "templates: []"
}

# ── share_validate ────────────────────────────────────────────────────

test_share_validate_ok_when_consistent() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco pack create "valid-pack"
    run_cco share validate
    assert_output_contains "valid"
}

test_share_validate_warns_stale_pack() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco pack create "will-delete"

    # Manually remove the pack dir but leave share.yml entry
    rm -rf "$CCO_PACKS_DIR/will-delete"

    # Validate should detect stale entry
    if run_cco share validate 2>/dev/null; then
        echo "ASSERTION FAILED: should have detected stale entry"
        return 1
    fi
}

test_share_validate_warns_missing_entry() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"

    # Create a pack dir manually (no share_refresh)
    mkdir -p "$CCO_PACKS_DIR/orphan-pack"
    printf 'name: orphan-pack\n' > "$CCO_PACKS_DIR/orphan-pack/pack.yml"

    # Validate should detect missing entry
    if run_cco share validate 2>/dev/null; then
        echo "ASSERTION FAILED: should have detected missing entry"
        return 1
    fi
}

test_share_validate_fails_without_share_yml() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    if run_cco share validate 2>/dev/null; then
        echo "ASSERTION FAILED: should fail without share.yml"
        return 1
    fi
}

# ── cco share show ────────────────────────────────────────────────────

test_share_show_displays_config_repo() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"
    run_cco share show
    assert_output_contains "Config Repo"
    assert_output_contains "Packs:"
    assert_output_contains "Templates:"
}

test_share_show_lists_packs() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco pack create "shown-pack"
    run_cco share show
    assert_output_contains "shown-pack"
}

test_share_show_fails_without_share_yml() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    if run_cco share show 2>/dev/null; then
        echo "ASSERTION FAILED: should fail without share.yml"
        return 1
    fi
}

# ── cco share refresh ────────────────────────────────────────────────

test_share_refresh_command_works() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"
    run_cco share refresh
    assert_output_contains "refreshed"
}
