#!/usr/bin/env bash
# tests/test_start_dry_run.sh — cco start --dry-run compose generation tests
#
# Verifies the docker-compose.yml generated by cmd_start --dry-run.
# No Docker daemon or running containers required.
# All tests assert on the generated file at projects/<name>/docker-compose.yml.

# ── Basic generation ──────────────────────────────────────────────────

test_dry_run_creates_compose_file() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_exists "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml"
}

test_dry_run_compose_is_valid_yaml() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_valid_compose "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml"
}

test_dry_run_compose_auto_generated_header() {
    # Compose file must have the auto-generated header comment
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "AUTO-GENERATED by cco CLI"
}

# ── Container and network naming (Design Invariant 4) ────────────────

test_dry_run_container_name_convention() {
    # Design Invariant 4: container name is cc-<project-name>
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "alpha-proj" "$(minimal_project_yml alpha-proj)"
    run_cco start "alpha-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/alpha-proj/docker-compose.yml" "container_name: cc-alpha-proj"
}

test_dry_run_network_name_convention() {
    # Design Invariant 4: network name is cc-<project-name>
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "alpha-proj" "$(minimal_project_yml alpha-proj)"
    run_cco start "alpha-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/alpha-proj/docker-compose.yml" "name: cc-alpha-proj"
    assert_file_contains "$CCO_PROJECTS_DIR/alpha-proj/docker-compose.yml" "driver: bridge"
}

# ── Required environment variables ───────────────────────────────────

test_dry_run_project_name_env_var() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "my-proj" "$(minimal_project_yml my-proj)"
    run_cco start "my-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/my-proj/docker-compose.yml" "PROJECT_NAME=my-proj"
}

test_dry_run_teammate_mode_env_var() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "TEAMMATE_MODE=tmux"
}

test_dry_run_agent_teams_env_var() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1"
}

# ── Volume mounts: global config (Design Invariant 5 - read-only) ────

test_dry_run_settings_json_mounted_readonly() {
    # Design Invariant 5: global config always :ro
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "settings.json:/home/claude/.claude/settings.json:ro"
}

test_dry_run_claude_md_mounted_readonly() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "CLAUDE.md:/home/claude/.claude/CLAUDE.md:ro"
}

test_dry_run_rules_mounted_readonly() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "rules:/home/claude/.claude/rules:ro"
}

test_dry_run_agents_mounted_readonly() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "agents:/home/claude/.claude/agents:ro"
}

test_dry_run_skills_mounted_readonly() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "skills:/home/claude/.claude/skills:ro"
}

# ── Volume mounts: git (Design Invariant 5 - read-only) ──────────────

test_dry_run_gitconfig_mounted_readonly() {
    # Design Invariant 5: git config always :ro
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" ".gitconfig:/home/claude/.gitconfig:ro"
}

test_dry_run_ssh_not_mounted() {
    # SSH keys are NOT mounted (auth is HTTPS via gh credential helper)
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_not_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" ".ssh"
}

# ── Volume mounts: auto memory (Design Invariant 3) ──────────────────

test_dry_run_auto_memory_exact_path() {
    # Design Invariant 3: claude-state MUST be mounted at this exact container path
    # /workspace → -workspace (root slash replaced by dash per Claude Code convention)
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" \
        "claude-state:/home/claude/.claude/projects/-workspace"
}

# ── Volume mounts: project config (Design Invariant 2 - read-write) ──

test_dry_run_project_claude_mounted_readwrite() {
    # Design Invariant 2: project .claude must be rw (no :ro)
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    local compose="$CCO_PROJECTS_DIR/test-proj/docker-compose.yml"
    assert_file_contains "$compose" "./.claude:/workspace/.claude"
    # Must NOT have :ro suffix on project config
    if grep -qF "./.claude:/workspace/.claude:ro" "$compose"; then
        echo "ASSERTION FAILED: project .claude must be rw, not :ro"
        return 1
    fi
}

# ── Docker socket (Docker-from-Docker) ───────────────────────────────

test_dry_run_docker_socket_mounted() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" \
        "/var/run/docker.sock:/var/run/docker.sock"
}

# ── Repository mounts ─────────────────────────────────────────────────

test_dry_run_single_repo_mounted() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local fake_repo="$tmpdir/my-repo"
    mkdir -p "$fake_repo"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos:
  - path: $fake_repo
    name: my-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" \
        "${fake_repo}:/workspace/my-repo"
}

test_dry_run_multi_repo_all_mounted() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local repo_a="$tmpdir/repo-a"
    local repo_b="$tmpdir/repo-b"
    mkdir -p "$repo_a" "$repo_b"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos:
  - path: $repo_a
    name: repo-a
  - path: $repo_b
    name: repo-b
YAML
)"
    run_cco start "test-proj" --dry-run
    local compose="$CCO_PROJECTS_DIR/test-proj/docker-compose.yml"
    assert_file_contains "$compose" "${repo_a}:/workspace/repo-a"
    assert_file_contains "$compose" "${repo_b}:/workspace/repo-b"
}

# ── Extra mounts ──────────────────────────────────────────────────────

test_dry_run_extra_mount_readonly() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local docs="$tmpdir/docs"
    mkdir -p "$docs"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
extra_mounts:
  - source: $docs
    target: /workspace/docs
    readonly: true
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" \
        "${docs}:/workspace/docs:ro"
}

test_dry_run_extra_mount_readwrite() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local rw_dir="$tmpdir/rw"
    mkdir -p "$rw_dir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
extra_mounts:
  - source: $rw_dir
    target: /workspace/rw
    readonly: false
YAML
)"
    run_cco start "test-proj" --dry-run
    local compose="$CCO_PROJECTS_DIR/test-proj/docker-compose.yml"
    assert_file_contains "$compose" "${rw_dir}:/workspace/rw"
    assert_file_not_contains "$compose" "${rw_dir}:/workspace/rw:ro"
}

# ── Custom ports and env vars ─────────────────────────────────────────

test_dry_run_custom_ports_in_compose() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports:
    - "5000:5000"
    - "9090:9090"
  env: {}
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    local compose="$CCO_PROJECTS_DIR/test-proj/docker-compose.yml"
    assert_file_contains "$compose" '"5000:5000"'
    assert_file_contains "$compose" '"9090:9090"'
}

test_dry_run_custom_env_vars_in_compose() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env:
    NODE_ENV: production
    DATABASE_URL: postgres://localhost/mydb
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    local compose="$CCO_PROJECTS_DIR/test-proj/docker-compose.yml"
    assert_file_contains "$compose" "NODE_ENV=production"
    assert_file_contains "$compose" "DATABASE_URL=postgres://localhost/mydb"
}

# ── Authentication ────────────────────────────────────────────────────

test_dry_run_oauth_no_api_key_in_compose() {
    # oauth auth → ANTHROPIC_API_KEY must NOT appear in compose file
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_not_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "ANTHROPIC_API_KEY"
}

test_dry_run_api_key_auth_in_compose() {
    # api_key auth → ANTHROPIC_API_KEY must appear in compose
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: api_key
docker:
  ports: []
  env: {}
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "ANTHROPIC_API_KEY"
}

# ── Knowledge packs (copied, not mounted) ────────────────────────────

test_dry_run_pack_knowledge_copied() {
    # Knowledge files are copied to .claude/packs/, not mounted as volumes
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_src="$tmpdir/pack-src"
    mkdir -p "$pack_src"
    echo "test knowledge" > "$pack_src/doc.md"
    create_pack "$tmpdir" "my-pack" "$(cat <<YAML
name: my-pack
knowledge:
  source: $pack_src
  files:
    - doc.md
YAML
)"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
packs:
  - my-pack
YAML
)"
    run_cco start "test-proj" --dry-run
    local copied="$CCO_PROJECTS_DIR/test-proj/.claude/packs/my-pack/doc.md"
    [[ -f "$copied" ]] || fail "Knowledge file not copied to $copied"
    assert_file_contains "$copied" "test knowledge"
}

# ── MCP server config ─────────────────────────────────────────────────

test_dry_run_global_mcp_mounted_when_present() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    # defaults already includes mcp.json
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "mcp-global.json:ro"
}

test_dry_run_global_mcp_not_mounted_when_absent() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    rm -f "$CCO_GLOBAL_DIR/.claude/mcp.json"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_not_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "mcp-global.json"
}

# ── Volume mount ordering (Design Invariant 6) ───────────────────────

test_dry_run_volume_order_auth_before_global_config() {
    # Design Invariant 6: auth (.claude.json) before global config (settings.json)
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    local compose="$CCO_PROJECTS_DIR/test-proj/docker-compose.yml"
    local auth_line settings_line
    auth_line=$(grep -n ".claude.json:" "$compose" | head -1 | cut -d: -f1)
    settings_line=$(grep -n "settings.json:ro" "$compose" | head -1 | cut -d: -f1)
    if [[ -z "$auth_line" || -z "$settings_line" ]]; then
        echo "ASSERTION FAILED: could not find auth or settings line in compose"
        return 1
    fi
    if [[ "$auth_line" -ge "$settings_line" ]]; then
        echo "ASSERTION FAILED: auth (.claude.json) must appear before global settings.json"
        echo "  auth at line: $auth_line"
        echo "  settings at line: $settings_line"
        return 1
    fi
}

test_dry_run_volume_order_global_before_project() {
    # Design Invariant 6: global config before project config
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    local compose="$CCO_PROJECTS_DIR/test-proj/docker-compose.yml"
    local settings_line project_line
    settings_line=$(grep -n "settings.json:ro" "$compose" | head -1 | cut -d: -f1)
    project_line=$(grep -n "./.claude:/workspace/.claude" "$compose" | head -1 | cut -d: -f1)
    if [[ -z "$settings_line" || -z "$project_line" ]]; then
        echo "ASSERTION FAILED: could not find settings or project config line"
        return 1
    fi
    if [[ "$settings_line" -ge "$project_line" ]]; then
        echo "ASSERTION FAILED: global settings must appear before project .claude"
        echo "  settings at line: $settings_line"
        echo "  project at line: $project_line"
        return 1
    fi
}

test_dry_run_volume_order_memory_before_git() {
    # Design Invariant 6: claude-state mount before git mounts
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    local compose="$CCO_PROJECTS_DIR/test-proj/docker-compose.yml"
    local memory_line git_line
    memory_line=$(grep -n "claude-state.*-workspace" "$compose" | head -1 | cut -d: -f1)
    git_line=$(grep -n ".gitconfig:ro" "$compose" | head -1 | cut -d: -f1)
    if [[ -z "$memory_line" || -z "$git_line" ]]; then
        echo "ASSERTION FAILED: could not find memory or git line"
        return 1
    fi
    if [[ "$memory_line" -ge "$git_line" ]]; then
        echo "ASSERTION FAILED: memory must appear before git mounts"
        echo "  memory at line: $memory_line"
        echo "  git at line: $git_line"
        return 1
    fi
}

test_dry_run_volume_order_git_before_docker_socket() {
    # Design Invariant 6: git mounts before docker socket
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    local compose="$CCO_PROJECTS_DIR/test-proj/docker-compose.yml"
    local git_line socket_line
    git_line=$(grep -n ".gitconfig:ro" "$compose" | head -1 | cut -d: -f1)
    socket_line=$(grep -n "docker.sock" "$compose" | head -1 | cut -d: -f1)
    if [[ -z "$git_line" || -z "$socket_line" ]]; then
        echo "ASSERTION FAILED: could not find git or docker socket line"
        return 1
    fi
    if [[ "$git_line" -ge "$socket_line" ]]; then
        echo "ASSERTION FAILED: git mounts must appear before docker socket"
        echo "  git at line: $git_line"
        echo "  socket at line: $socket_line"
        return 1
    fi
}

# ── Custom Docker image ──────────────────────────────────────────────

test_dry_run_custom_image() {
    # docker.image in project.yml overrides the default image
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  image: my-custom-image:v2
  ports: []
  env: {}
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "image: my-custom-image:v2"
}

test_dry_run_default_image_when_no_docker_image() {
    # Without docker.image, default image is used
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "image: claude-orchestrator:latest"
}

# ── Docker socket toggle ─────────────────────────────────────────────

test_dry_run_docker_socket_mounted_by_default() {
    # Docker socket is mounted when mount_socket is not specified
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" \
        "/var/run/docker.sock:/var/run/docker.sock"
}

test_dry_run_docker_socket_not_mounted_when_disabled() {
    # docker.mount_socket: false disables Docker socket mount
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  mount_socket: false
  ports: []
  env: {}
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_file_not_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "docker.sock"
}

# ── Project setup.sh mount ───────────────────────────────────────────

test_dry_run_setup_sh_mounted_when_exists() {
    # setup.sh in project dir → mounted read-only in compose
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    echo '#!/bin/bash' > "$CCO_PROJECTS_DIR/test-proj/setup.sh"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" \
        "./setup.sh:/workspace/setup.sh:ro"
}

test_dry_run_setup_sh_not_mounted_when_missing() {
    # No setup.sh → no mount in compose
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_not_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "setup.sh"
}

# ── Project mcp-packages.txt mount ──────────────────────────────────

test_dry_run_mcp_packages_mounted_when_exists() {
    # mcp-packages.txt in project dir → mounted read-only in compose
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    echo '# packages' > "$CCO_PROJECTS_DIR/test-proj/mcp-packages.txt"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" \
        "./mcp-packages.txt:/workspace/mcp-packages.txt:ro"
}

test_dry_run_mcp_packages_not_mounted_when_missing() {
    # No mcp-packages.txt → no mount in compose
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_not_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "mcp-packages.txt"
}

# ── Browser MCP integration ────────────────────────────────────────

test_browser_disabled_by_default() {
    # No browser section → no extra_hosts, no .managed/ mount
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    local compose="$CCO_PROJECTS_DIR/test-proj/docker-compose.yml"
    assert_file_not_contains "$compose" "extra_hosts"
    assert_file_not_contains "$compose" ".managed"
    assert_file_not_exists "$CCO_PROJECTS_DIR/test-proj/.managed/browser.json"
}

test_browser_host_mode_extra_hosts() {
    # browser.enabled: true → extra_hosts with host.docker.internal
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
browser:
  enabled: true
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "host.docker.internal:host-gateway"
}

test_browser_mcp_json_generated() {
    # browser.enabled: true → .managed/browser.json created with correct content
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
browser:
  enabled: true
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    local mcp_file="$CCO_PROJECTS_DIR/test-proj/.managed/browser.json"
    assert_file_exists "$mcp_file"
    assert_file_contains "$mcp_file" "chrome-devtools-mcp"
    assert_file_contains "$mcp_file" "localhost:9222"
}

test_browser_mcp_mounted_in_compose() {
    # browser.enabled: true → .managed/ dir mounted read-only in compose
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
browser:
  enabled: true
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" \
        "./.managed:/workspace/.managed:ro"
}

test_browser_custom_cdp_port() {
    # browser.cdp_port: 9223 → browserUrl uses port 9223
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
browser:
  enabled: true
  cdp_port: 9223
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/.managed/browser.json" "localhost:9223"
}

test_browser_chrome_flag_override() {
    # --chrome flag activates browser even without browser.enabled in project.yml
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --chrome --dry-run
    local compose="$CCO_PROJECTS_DIR/test-proj/docker-compose.yml"
    assert_file_contains "$compose" "host.docker.internal:host-gateway"
    assert_file_contains "$compose" "./.managed:/workspace/.managed:ro"
    assert_file_exists "$CCO_PROJECTS_DIR/test-proj/.managed/browser.json"
}

test_browser_disabled_no_mcp_file() {
    # browser.enabled: false → no .managed/browser.json created
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
browser:
  enabled: false
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_file_not_exists "$CCO_PROJECTS_DIR/test-proj/.managed/browser.json"
}

test_browser_mcp_privacy_flags() {
    # Generated config always contains privacy flags
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
browser:
  enabled: true
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    local mcp_file="$CCO_PROJECTS_DIR/test-proj/.managed/browser.json"
    assert_file_contains "$mcp_file" "--no-usage-statistics"
    assert_file_contains "$mcp_file" "--no-performance-crux"
}

test_browser_mcp_args_appended() {
    # mcp_args: ["--slim"] → appended after privacy flags
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
browser:
  enabled: true
  mcp_args:
    - "--slim"
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    local mcp_file="$CCO_PROJECTS_DIR/test-proj/.managed/browser.json"
    assert_file_contains "$mcp_file" "--slim"
}

test_browser_user_mcp_json_untouched() {
    # User's mcp.json is not modified when browser is enabled (browser config goes to .managed/)
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
browser:
  enabled: true
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    echo '{"mcpServers":{"github":{}}}' > "$CCO_PROJECTS_DIR/test-proj/mcp.json"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/mcp.json" '"github"'
    assert_file_not_contains "$CCO_PROJECTS_DIR/test-proj/mcp.json" "chrome-devtools"
}

test_browser_port_written_to_file() {
    # .managed/.browser-port is created with the effective port
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
browser:
  enabled: true
  cdp_port: 9225
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    local port_file="$CCO_PROJECTS_DIR/test-proj/.managed/.browser-port"
    assert_file_exists "$port_file"
    assert_equals "9225" "$(cat "$port_file")"
}

test_browser_dry_run_shows_browser_info() {
    # Dry-run output includes browser mode and port info
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
browser:
  enabled: true
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_output_contains "Browser: host mode (CDP proxy"
    assert_output_contains ".managed/browser.json"
}

test_browser_cdp_port_env_in_compose() {
    # CDP_PORT env var present in compose when browser host mode enabled
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
browser:
  enabled: true
  cdp_port: 9225
repos:
  - path: $CCO_DUMMY_REPO
    name: dummy-repo
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "CDP_PORT=9225"
}

test_browser_cdp_port_env_absent_when_disabled() {
    # CDP_PORT env var NOT in compose when browser is disabled
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_not_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" "CDP_PORT"
}
