#!/usr/bin/env bash
# tests/test_project_publish.sh — cco project publish tests

# ── Helpers ─────────────────────────────────────────────────────────

_create_empty_bare_remote() {
    local tmpdir="$1"
    local bare_dir="$tmpdir/publish-remote.git"
    local work_dir="$tmpdir/init-work"
    mkdir -p "$work_dir"
    git -C "$work_dir" init -q
    cat > "$work_dir/manifest.yml" <<'YAML'
# Auto-generated by cco
name: ""
description: ""

packs: []

templates: []
YAML
    git -C "$work_dir" add -A
    git -C "$work_dir" commit -q -m "init"
    git init --bare -q "$bare_dir"
    git -C "$work_dir" remote add origin "$bare_dir"
    git -C "$work_dir" push -q origin main 2>/dev/null || \
        git -C "$work_dir" push -q origin master 2>/dev/null
    rm -rf "$work_dir"
    echo "$bare_dir"
}

_create_test_project() {
    local name="$1"
    local project_dir="$CCO_PROJECTS_DIR/$name"
    mkdir -p "$project_dir/.claude/rules" "$project_dir/.cco/claude-state" "$project_dir/memory"

    cat > "$project_dir/project.yml" <<YAML
name: $name
description: "Test project $name"
repos:
  - path: ~/projects/my-repo
    name: my-repo
docker:
  ports:
    - "3000:3000"
  env: {}
auth:
  method: oauth

packs:
  - test-pack
YAML

    cat > "$project_dir/.claude/CLAUDE.md" <<'MD'
# Project
## Overview
Test project
MD
    echo "rule: follow conventions" > "$project_dir/.claude/rules/style.md"

    # Create runtime files that should be excluded
    echo "generated" > "$project_dir/.cco/docker-compose.yml"
    mkdir -p "$project_dir/.cco/managed" "$project_dir/.claude/.cco"
    echo "{}" > "$project_dir/.cco/managed/mcp.json"
    echo "pack: stuff" > "$project_dir/.claude/.cco/pack-manifest"
    echo "schema_version: 1" > "$project_dir/.cco/meta"
    echo "SECRET=pass" > "$project_dir/secrets.env"
}

_create_test_pack() {
    local name="$1"
    mkdir -p "$CCO_PACKS_DIR/$name/knowledge"
    cat > "$CCO_PACKS_DIR/$name/pack.yml" <<YAML
name: $name
description: "Pack $name"
knowledge:
  files:
    - path: docs.md
YAML
    echo "# Docs" > "$CCO_PACKS_DIR/$name/knowledge/docs.md"
}

# ── Tests ───────────────────────────────────────────────────────────

test_project_publish_creates_template() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    _create_test_project "my-proj"
    _create_test_pack "test-pack"

    local bare_dir
    bare_dir=$(_create_empty_bare_remote "$tmpdir")
    run_cco remote add target "$bare_dir"
    run_cco project publish my-proj target --force
    assert_output_contains "Published"

    local verify_dir="$tmpdir/verify"
    git clone -q "$bare_dir" "$verify_dir"
    [[ -f "$verify_dir/templates/my-proj/project.yml" ]] || {
        echo "ASSERTION FAILED: project.yml not in remote templates/"
        return 1
    }
    [[ -f "$verify_dir/templates/my-proj/.claude/CLAUDE.md" ]] || {
        echo "ASSERTION FAILED: CLAUDE.md not in remote"
        return 1
    }
}

test_project_publish_excludes_runtime_files() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    _create_test_project "my-proj"
    _create_test_pack "test-pack"

    local bare_dir
    bare_dir=$(_create_empty_bare_remote "$tmpdir")
    run_cco remote add target "$bare_dir"
    run_cco project publish my-proj target --force

    local verify_dir="$tmpdir/verify"
    git clone -q "$bare_dir" "$verify_dir"
    local tmpl="$verify_dir/templates/my-proj"

    [[ ! -f "$tmpl/.cco/docker-compose.yml" ]] || {
        echo "ASSERTION FAILED: .cco/docker-compose.yml should be excluded"
        return 1
    }
    [[ ! -d "$tmpl/.cco/managed" ]] || {
        echo "ASSERTION FAILED: .cco/managed/ should be excluded"
        return 1
    }
    [[ ! -f "$tmpl/.claude/.cco/pack-manifest" ]] || {
        echo "ASSERTION FAILED: .claude/.cco/pack-manifest should be excluded"
        return 1
    }
    [[ ! -f "$tmpl/.cco/meta" ]] || {
        echo "ASSERTION FAILED: .cco/meta should be excluded"
        return 1
    }
    [[ ! -d "$tmpl/.cco/claude-state" ]] || {
        echo "ASSERTION FAILED: .cco/claude-state/ should be excluded"
        return 1
    }
    [[ ! -f "$tmpl/secrets.env" ]] || {
        echo "ASSERTION FAILED: secrets.env should be excluded"
        return 1
    }
    [[ ! -d "$tmpl/memory" ]] || {
        echo "ASSERTION FAILED: memory/ should be excluded"
        return 1
    }
}

test_project_publish_bundles_packs() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    _create_test_project "my-proj"
    _create_test_pack "test-pack"

    local bare_dir
    bare_dir=$(_create_empty_bare_remote "$tmpdir")
    run_cco remote add target "$bare_dir"
    run_cco project publish my-proj target --force

    local verify_dir="$tmpdir/verify"
    git clone -q "$bare_dir" "$verify_dir"
    [[ -f "$verify_dir/packs/test-pack/pack.yml" ]] || {
        echo "ASSERTION FAILED: bundled pack not found in remote"
        return 1
    }
    assert_output_contains "test-pack"
}

test_project_publish_no_packs_flag() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    _create_test_project "my-proj"
    _create_test_pack "test-pack"

    local bare_dir
    bare_dir=$(_create_empty_bare_remote "$tmpdir")
    run_cco remote add target "$bare_dir"
    run_cco project publish my-proj target --force --no-packs

    local verify_dir="$tmpdir/verify"
    git clone -q "$bare_dir" "$verify_dir"
    [[ ! -d "$verify_dir/packs/test-pack" ]] || {
        echo "ASSERTION FAILED: packs should not be bundled with --no-packs"
        return 1
    }
}

test_project_publish_reverse_templates_repos() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    _create_test_project "my-proj"
    _create_test_pack "test-pack"

    local bare_dir
    bare_dir=$(_create_empty_bare_remote "$tmpdir")
    run_cco remote add target "$bare_dir"
    run_cco project publish my-proj target --force

    local verify_dir="$tmpdir/verify"
    git clone -q "$bare_dir" "$verify_dir"
    local published_yml="$verify_dir/templates/my-proj/project.yml"
    grep -q '{{REPO_MY_REPO}}' "$published_yml" || {
        echo "ASSERTION FAILED: repo path should be reverse-templated"
        cat "$published_yml"
        return 1
    }
}

test_project_publish_adds_url_from_git_remote() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    _create_test_pack "test-pack"

    # Create a real git repo so the URL can be inferred
    local repo_dir="$tmpdir/projects/my-repo"
    mkdir -p "$repo_dir"
    git -C "$repo_dir" init -q
    git -C "$repo_dir" remote add origin "git@github.com:test/my-repo.git"

    # Create project pointing to that repo
    local project_dir="$CCO_PROJECTS_DIR/url-proj"
    mkdir -p "$project_dir/.claude/rules" "$project_dir/.cco/claude-state" "$project_dir/memory"
    cat > "$project_dir/project.yml" <<YAML
name: url-proj
description: "Test"
repos:
  - path: $repo_dir
    name: my-repo
docker:
  ports: []
  env: {}
auth:
  method: oauth
packs:
  - test-pack
YAML
    cat > "$project_dir/.claude/CLAUDE.md" <<'MD'
# Project
MD

    local bare_dir
    bare_dir=$(_create_empty_bare_remote "$tmpdir")
    run_cco remote add target "$bare_dir"
    run_cco project publish url-proj target --force

    local verify_dir="$tmpdir/verify"
    git clone -q "$bare_dir" "$verify_dir"
    local published_yml="$verify_dir/templates/url-proj/project.yml"
    grep -q 'url: git@github.com:test/my-repo.git' "$published_yml" || {
        echo "ASSERTION FAILED: url: field not added from git remote"
        cat "$published_yml"
        return 1
    }
}

test_project_publish_updates_manifest() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    _create_test_project "my-proj"
    _create_test_pack "test-pack"

    local bare_dir
    bare_dir=$(_create_empty_bare_remote "$tmpdir")
    run_cco remote add target "$bare_dir"
    run_cco project publish my-proj target --force

    local verify_dir="$tmpdir/verify"
    git clone -q "$bare_dir" "$verify_dir"
    grep -q "my-proj" "$verify_dir/manifest.yml" || {
        echo "ASSERTION FAILED: manifest should list template"
        return 1
    }
}

test_project_publish_dry_run() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    _create_test_project "my-proj"
    _create_test_pack "test-pack"

    local bare_dir
    bare_dir=$(_create_empty_bare_remote "$tmpdir")
    run_cco remote add target "$bare_dir"
    run_cco project publish my-proj target --dry-run
    assert_output_contains "Dry run"

    local verify_dir="$tmpdir/verify"
    git clone -q "$bare_dir" "$verify_dir"
    [[ ! -d "$verify_dir/templates/my-proj" ]] || {
        echo "ASSERTION FAILED: dry run should not push"
        return 1
    }
}

test_project_publish_nonexistent_fails() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    if run_cco project publish ghost target 2>/dev/null; then
        echo "ASSERTION FAILED: should fail for nonexistent project"
        return 1
    fi
}

test_project_publish_no_remote_fails() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    _create_test_project "my-proj"
    if run_cco project publish my-proj 2>/dev/null; then
        echo "ASSERTION FAILED: should fail without remote"
        return 1
    fi
}

test_project_publish_help() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    run_cco project publish --help
    assert_output_contains "Publish a project"
}
