#!/usr/bin/env bash
# tests/test_manifest.sh — manifest.yml management tests
#
# Verifies manifest_init, manifest_refresh, manifest_validate, and the
# cco manifest CLI commands. Also tests backward compat alias (cco share).

# ── manifest_init ────────────────────────────────────────────────────

test_manifest_init_creates_manifest_yml() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"
    assert_file_exists "$CCO_USER_CONFIG_DIR/manifest.yml"
}

test_manifest_init_contains_packs_section() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "packs:"
}

test_manifest_init_contains_templates_section() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "templates:"
}

test_manifest_init_idempotent() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"

    # Modify manifest.yml
    printf '\n# USER_CANARY\n' >> "$CCO_USER_CONFIG_DIR/manifest.yml"

    # Second init should NOT overwrite
    run_cco init --lang "English"
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "USER_CANARY"
}

test_cco_share_command_errors() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"
    # cco share should error with migration hint
    if run_cco share refresh 2>/dev/null; then
        echo "ASSERTION FAILED: 'cco share' should error, not succeed"
        return 1
    fi
}

# ── manifest_refresh ─────────────────────────────────────────────────

test_manifest_refresh_lists_packs() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco pack create "alpha-pack"
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "alpha-pack"
}

test_manifest_refresh_removes_deleted_pack() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco pack create "temp-pack"
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "temp-pack"
    run_cco pack remove "temp-pack"
    assert_file_not_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "temp-pack"
}

test_manifest_refresh_multiple_packs() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco pack create "pack-a"
    run_cco pack create "pack-b"
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "pack-a"
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "pack-b"
}

test_manifest_refresh_preserves_name_and_description() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"

    # Set repo name and description
    cat > "$CCO_USER_CONFIG_DIR/manifest.yml" <<'YAML'
# Auto-generated by cco
name: "my-config"
description: "My personal config"

packs: []

templates: []
YAML

    # Create a pack (triggers refresh)
    run_cco pack create "new-pack"

    # Name and description should survive
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "my-config"
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "My personal config"
}

test_manifest_refresh_includes_templates() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"

    # Create a template directory manually
    mkdir -p "$CCO_TEMPLATES_DIR/my-template"

    run_cco manifest refresh
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "my-template"
}

test_manifest_refresh_empty_when_no_packs_or_templates() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"
    run_cco manifest refresh
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "packs: []"
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "templates: []"
}

# ── manifest_validate ────────────────────────────────────────────────

test_manifest_validate_ok_when_consistent() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco pack create "valid-pack"
    run_cco manifest validate
    assert_output_contains "valid"
}

test_manifest_validate_warns_stale_pack() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco pack create "will-delete"

    # Manually remove the pack dir but leave manifest.yml entry
    rm -rf "$CCO_PACKS_DIR/will-delete"

    # Validate should detect stale entry
    if run_cco manifest validate 2>/dev/null; then
        echo "ASSERTION FAILED: should have detected stale entry"
        return 1
    fi
}

test_manifest_validate_warns_missing_entry() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"

    # Create a pack dir manually (no manifest_refresh)
    mkdir -p "$CCO_PACKS_DIR/orphan-pack"
    printf 'name: orphan-pack\n' > "$CCO_PACKS_DIR/orphan-pack/pack.yml"

    # Validate should detect missing entry
    if run_cco manifest validate 2>/dev/null; then
        echo "ASSERTION FAILED: should have detected missing entry"
        return 1
    fi
}

test_manifest_validate_fails_without_manifest_yml() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    if run_cco manifest validate 2>/dev/null; then
        echo "ASSERTION FAILED: should fail without manifest.yml"
        return 1
    fi
}

# ── cco manifest show ────────────────────────────────────────────────

test_manifest_show_displays_config_repo() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"
    run_cco manifest show
    assert_output_contains "Config Repo"
    assert_output_contains "Packs:"
    assert_output_contains "Templates:"
}

test_manifest_show_lists_packs() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco pack create "shown-pack"
    run_cco manifest show
    assert_output_contains "shown-pack"
}

test_manifest_show_fails_without_manifest_yml() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    if run_cco manifest show 2>/dev/null; then
        echo "ASSERTION FAILED: should fail without manifest.yml"
        return 1
    fi
}

# ── cco manifest refresh ────────────────────────────────────────────

test_manifest_refresh_command_works() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"
    run_cco manifest refresh
    assert_output_contains "refreshed"
}

# ── manifest refresh: template packs and repos ───────────────────────

test_manifest_refresh_includes_template_packs() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"

    # Create a template with packs and repos
    mkdir -p "$CCO_USER_CONFIG_DIR/templates/my-tmpl"
    cat > "$CCO_USER_CONFIG_DIR/templates/my-tmpl/project.yml" <<'YAML'
name: my-tmpl
repos:
  - path: "{{REPO_API}}"
    name: backend-api
    url: git@github.com:acme/api.git
packs:
  - alpha
  - beta
YAML

    run_cco manifest refresh
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "packs: [alpha, beta]"
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "backend-api"
}

test_manifest_refresh_template_without_packs_or_repos() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"

    mkdir -p "$CCO_USER_CONFIG_DIR/templates/simple"
    cat > "$CCO_USER_CONFIG_DIR/templates/simple/project.yml" <<'YAML'
name: simple
repos: []
packs: []
YAML

    run_cco manifest refresh
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "simple"
}

# ── migration: share.yml → manifest.yml ──────────────────────────────

test_migration_renames_share_to_manifest() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"

    # Simulate legacy state: rename manifest.yml back to share.yml
    mv "$CCO_USER_CONFIG_DIR/manifest.yml" "$CCO_USER_CONFIG_DIR/share.yml"
    printf '\n# LEGACY_CONTENT\n' >> "$CCO_USER_CONFIG_DIR/share.yml"

    # Source and run migration directly
    source "$REPO_ROOT/migrations/global/004_rename_share_to_manifest.sh"
    migrate "$CCO_USER_CONFIG_DIR/global/.claude"

    assert_file_exists "$CCO_USER_CONFIG_DIR/manifest.yml"
    assert_file_contains "$CCO_USER_CONFIG_DIR/manifest.yml" "LEGACY_CONTENT"
    assert_file_not_exists "$CCO_USER_CONFIG_DIR/share.yml"
}

test_migration_idempotent_when_already_migrated() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    run_cco init --lang "English"

    # Already has manifest.yml, no share.yml — migration should be a no-op
    source "$REPO_ROOT/migrations/global/004_rename_share_to_manifest.sh"
    migrate "$CCO_USER_CONFIG_DIR/global/.claude"

    assert_file_exists "$CCO_USER_CONFIG_DIR/manifest.yml"
}
