#!/usr/bin/env bash
# tests/test_packs.sh — knowledge pack generation tests
#
# Verifies that .claude/packs.md is correctly generated with instructional file list.
# Design Invariant 7: format must be - /workspace/.packs/<name>/<file>

# Helper: create a standard single-pack project for testing
_create_pack_project() {
    local tmpdir="$1"
    local pack_name="${2:-my-pack}"
    local pack_src="$tmpdir/pack-src-${pack_name}"
    mkdir -p "$pack_src"
    create_pack "$tmpdir" "$pack_name" "$(cat <<YAML
name: $pack_name
source: $pack_src
target: /workspace/.packs/$pack_name
files:
  - overview.md
  - conventions.md
YAML
)"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - $pack_name
YAML
)"
    echo "$pack_src"  # return pack source path for assertions
}

test_packs_md_file_is_created() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    _create_pack_project "$tmpdir" > /dev/null
    run_cco start "test-proj" --dry-run
    assert_file_exists "$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"
}

test_packs_md_has_auto_generated_header() {
    # packs.md must have the auto-generated comment and instructional text
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    _create_pack_project "$tmpdir" > /dev/null
    run_cco start "test-proj" --dry-run
    local packs_md="$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"
    assert_file_contains "$packs_md" "Auto-generated by cco start"
    assert_file_contains "$packs_md" "Read them proactively"
}

test_packs_md_file_list_format() {
    # Design Invariant 7: each file must use "- /workspace/.packs/<name>/<file>" format
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_src
    pack_src=$(_create_pack_project "$tmpdir" "my-pack")
    run_cco start "test-proj" --dry-run
    local packs_md="$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/my-pack/overview.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/my-pack/conventions.md"
}

test_packs_md_one_line_per_file() {
    # Each file in pack.yml gets its own @import line
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_src="$tmpdir/pack-src"
    mkdir -p "$pack_src"
    create_pack "$tmpdir" "multi-file-pack" "$(cat <<YAML
name: multi-file-pack
source: $pack_src
target: /workspace/.packs/multi-file-pack
files:
  - doc-a.md
  - doc-b.md
  - doc-c.md
YAML
)"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - multi-file-pack
YAML
)"
    run_cco start "test-proj" --dry-run
    local packs_md="$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/multi-file-pack/doc-a.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/multi-file-pack/doc-b.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/multi-file-pack/doc-c.md"
}

test_packs_md_multiple_packs_all_files_present() {
    # Multiple packs → all files from all packs in packs.md
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local src_a="$tmpdir/pack-a-src"
    local src_b="$tmpdir/pack-b-src"
    mkdir -p "$src_a" "$src_b"
    create_pack "$tmpdir" "pack-a" "$(cat <<YAML
name: pack-a
source: $src_a
target: /workspace/.packs/pack-a
files:
  - a-overview.md
YAML
)"
    create_pack "$tmpdir" "pack-b" "$(cat <<YAML
name: pack-b
source: $src_b
target: /workspace/.packs/pack-b
files:
  - b-guide.md
YAML
)"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - pack-a
  - pack-b
YAML
)"
    run_cco start "test-proj" --dry-run
    local packs_md="$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/pack-a/a-overview.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/pack-b/b-guide.md"
}

test_packs_md_removed_when_no_packs() {
    # If project has no packs section, a stale packs.md must be removed
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"

    # Pre-create a stale packs.md (left from a previous run)
    printf '<!-- stale -->\n@/workspace/.packs/old/file.md\n' \
        > "$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"

    run_cco start "test-proj" --dry-run

    # The stale file must be deleted
    if [[ -f "$CCO_PROJECTS_DIR/test-proj/.claude/packs.md" ]]; then
        echo "ASSERTION FAILED: stale packs.md should have been removed when project has no packs"
        return 1
    fi
}

test_packs_md_missing_pack_silently_skipped() {
    # A pack referenced in project.yml but missing pack.yml is silently skipped
    # (bin/cco line 647: [[ ! -f "$pack_yml" ]] && continue — no die/warn)
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - nonexistent-pack
YAML
)"
    # Must not fail even though the pack doesn't exist
    run_cco start "test-proj" --dry-run
    # Compose file should still be generated
    assert_file_exists "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml"
}

test_packs_md_description_included_when_present() {
    # Object-format file entry with description: outputs "- path — description"
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_src="$tmpdir/pack-src"
    mkdir -p "$pack_src"
    create_pack "$tmpdir" "desc-pack" "$(cat <<YAML
name: desc-pack
source: $pack_src
target: /workspace/.packs/desc-pack
files:
  - path: guide.md
    description: "Read when working on guides"
YAML
)"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - desc-pack
YAML
)"
    run_cco start "test-proj" --dry-run
    local packs_md="$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/desc-pack/guide.md — Read when working on guides"
}

test_packs_md_no_description_shows_path_only() {
    # String-format file entry (no description) outputs "- path" without dash-dash
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_src="$tmpdir/pack-src"
    mkdir -p "$pack_src"
    create_pack "$tmpdir" "nodesc-pack" "$(cat <<YAML
name: nodesc-pack
source: $pack_src
target: /workspace/.packs/nodesc-pack
files:
  - notes.md
YAML
)"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - nodesc-pack
YAML
)"
    run_cco start "test-proj" --dry-run
    local packs_md="$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/nodesc-pack/notes.md"
    # The file entry line must NOT have a description suffix " — ..."
    if grep -Fe "notes.md" "$packs_md" | grep -qFe " — "; then
        echo "ASSERTION FAILED: packs.md should not contain description suffix when no description is set"
        return 1
    fi
}
