#!/usr/bin/env bash
# tests/test_packs.sh — knowledge pack generation tests
#
# Verifies that .claude/packs.md is correctly generated with instructional file list.
# Design Invariant 7: format must be - /workspace/.packs/<name>/<file>

# Helper: create a standard single-pack project for testing (new schema)
_create_pack_project() {
    local tmpdir="$1"
    local pack_name="${2:-my-pack}"
    local pack_src="$tmpdir/pack-src-${pack_name}"
    mkdir -p "$pack_src"
    create_pack "$tmpdir" "$pack_name" "$(cat <<YAML
name: $pack_name
knowledge:
  source: $pack_src
  files:
    - overview.md
    - conventions.md
YAML
)"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - $pack_name
YAML
)"
    echo "$pack_src"  # return pack source path for assertions
}

test_packs_md_file_is_created() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    _create_pack_project "$tmpdir" > /dev/null
    run_cco start "test-proj" --dry-run
    assert_file_exists "$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"
}

test_packs_md_has_auto_generated_header() {
    # packs.md must have the auto-generated comment and instructional text
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    _create_pack_project "$tmpdir" > /dev/null
    run_cco start "test-proj" --dry-run
    local packs_md="$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"
    assert_file_contains "$packs_md" "Auto-generated by cco start"
    assert_file_contains "$packs_md" "Read the relevant files BEFORE starting"
}

test_packs_md_file_list_format() {
    # Design Invariant 7: each file must use "- /workspace/.packs/<name>/<file>" format
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_src
    pack_src=$(_create_pack_project "$tmpdir" "my-pack")
    run_cco start "test-proj" --dry-run
    local packs_md="$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/my-pack/overview.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/my-pack/conventions.md"
}

test_packs_md_one_line_per_file() {
    # Each file in pack.yml knowledge.files gets its own list entry
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_src="$tmpdir/pack-src"
    mkdir -p "$pack_src"
    create_pack "$tmpdir" "multi-file-pack" "$(cat <<YAML
name: multi-file-pack
knowledge:
  source: $pack_src
  files:
    - doc-a.md
    - doc-b.md
    - doc-c.md
YAML
)"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - multi-file-pack
YAML
)"
    run_cco start "test-proj" --dry-run
    local packs_md="$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/multi-file-pack/doc-a.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/multi-file-pack/doc-b.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/multi-file-pack/doc-c.md"
}

test_packs_md_multiple_packs_all_files_present() {
    # Multiple packs → all files from all packs in packs.md
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local src_a="$tmpdir/pack-a-src"
    local src_b="$tmpdir/pack-b-src"
    mkdir -p "$src_a" "$src_b"
    create_pack "$tmpdir" "pack-a" "$(cat <<YAML
name: pack-a
knowledge:
  source: $src_a
  files:
    - a-overview.md
YAML
)"
    create_pack "$tmpdir" "pack-b" "$(cat <<YAML
name: pack-b
knowledge:
  source: $src_b
  files:
    - b-guide.md
YAML
)"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - pack-a
  - pack-b
YAML
)"
    run_cco start "test-proj" --dry-run
    local packs_md="$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/pack-a/a-overview.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/pack-b/b-guide.md"
}

test_packs_md_removed_when_no_packs() {
    # If project has no packs section, a stale packs.md must be removed
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"

    # Pre-create a stale packs.md (left from a previous run)
    printf '<!-- stale -->\n@/workspace/.packs/old/file.md\n' \
        > "$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"

    run_cco start "test-proj" --dry-run

    # The stale file must be deleted
    if [[ -f "$CCO_PROJECTS_DIR/test-proj/.claude/packs.md" ]]; then
        echo "ASSERTION FAILED: stale packs.md should have been removed when project has no packs"
        return 1
    fi
}

test_packs_md_missing_pack_silently_skipped() {
    # A pack referenced in project.yml but missing pack.yml is silently skipped
    # (bin/cco line 647: [[ ! -f "$pack_yml" ]] && continue — no die/warn)
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - nonexistent-pack
YAML
)"
    # Must not fail even though the pack doesn't exist
    run_cco start "test-proj" --dry-run
    # Compose file should still be generated
    assert_file_exists "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml"
}

test_packs_md_description_included_when_present() {
    # Object-format file entry with description: outputs "- path — description"
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_src="$tmpdir/pack-src"
    mkdir -p "$pack_src"
    create_pack "$tmpdir" "desc-pack" "$(cat <<YAML
name: desc-pack
knowledge:
  source: $pack_src
  files:
    - path: guide.md
      description: "Read when working on guides"
YAML
)"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - desc-pack
YAML
)"
    run_cco start "test-proj" --dry-run
    local packs_md="$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/desc-pack/guide.md — Read when working on guides"
}

test_packs_md_no_description_shows_path_only() {
    # String-format file entry (no description) outputs "- path" without dash-dash
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_src="$tmpdir/pack-src"
    mkdir -p "$pack_src"
    create_pack "$tmpdir" "nodesc-pack" "$(cat <<YAML
name: nodesc-pack
knowledge:
  source: $pack_src
  files:
    - notes.md
YAML
)"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - nodesc-pack
YAML
)"
    run_cco start "test-proj" --dry-run
    local packs_md="$CCO_PROJECTS_DIR/test-proj/.claude/packs.md"
    assert_file_contains "$packs_md" "- /workspace/.packs/nodesc-pack/notes.md"
    # The file entry line must NOT have a description suffix " — ..."
    if grep -Fe "notes.md" "$packs_md" | grep -qFe " — "; then
        echo "ASSERTION FAILED: packs.md should not contain description suffix when no description is set"
        return 1
    fi
}

# ── workspace.yml generation ──────────────────────────────────────────

test_workspace_yml_is_generated() {
    # cco start must create .claude/workspace.yml
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_exists "$CCO_PROJECTS_DIR/test-proj/.claude/workspace.yml"
}

test_workspace_yml_contains_project_name() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "my-project" "$(minimal_project_yml my-project)"
    run_cco start "my-project" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/my-project/.claude/workspace.yml" "project: my-project"
}

test_workspace_yml_contains_repo_names() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local repo_a="$tmpdir/repo-a"
    local repo_b="$tmpdir/repo-b"
    mkdir -p "$repo_a" "$repo_b"
    create_project "$tmpdir" "test-proj" "$(cat <<YAML
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos:
  - path: $repo_a
    name: repo-a
  - path: $repo_b
    name: repo-b
YAML
)"
    run_cco start "test-proj" --dry-run
    local ws="$CCO_PROJECTS_DIR/test-proj/.claude/workspace.yml"
    assert_file_contains "$ws" "name: repo-a"
    assert_file_contains "$ws" "name: repo-b"
}

test_workspace_yml_contains_pack_names() {
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_src="$tmpdir/pack-src"
    mkdir -p "$pack_src"
    create_pack "$tmpdir" "my-pack" "$(cat <<YAML
name: my-pack
knowledge:
  source: $pack_src
  files:
    - guide.md
YAML
)"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - my-pack
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/.claude/workspace.yml" "- my-pack"
}

# ── project.yml mount ─────────────────────────────────────────────────

test_project_yml_mounted_in_compose() {
    # project.yml must be mounted at /workspace/.claude/project.yml (rw)
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    create_project "$tmpdir" "test-proj" "$(minimal_project_yml test-proj)"
    run_cco start "test-proj" --dry-run
    assert_file_contains "$CCO_PROJECTS_DIR/test-proj/docker-compose.yml" \
        "./project.yml:/workspace/.claude/project.yml"
}

# ── pack skills / agents / rules copy ────────────────────────────────

test_pack_skills_copied_to_project_claude() {
    # Skills defined in pack are copied to projects/<n>/.claude/skills/
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    # Create pack with a skill
    local pack_dir="$tmpdir/global/packs/skill-pack"
    mkdir -p "$pack_dir/skills/deploy"
    echo "Deploy skill" > "$pack_dir/skills/deploy/SKILL.md"
    printf 'name: skill-pack\nskills:\n  - deploy\n' > "$pack_dir/pack.yml"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - skill-pack
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_file_exists "$CCO_PROJECTS_DIR/test-proj/.claude/skills/deploy/SKILL.md"
}

test_pack_agents_copied_to_project_claude() {
    # Agents defined in pack are copied to projects/<n>/.claude/agents/
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_dir="$tmpdir/global/packs/agent-pack"
    mkdir -p "$pack_dir/agents"
    echo "Agent spec" > "$pack_dir/agents/devops.md"
    printf 'name: agent-pack\nagents:\n  - devops.md\n' > "$pack_dir/pack.yml"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - agent-pack
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_file_exists "$CCO_PROJECTS_DIR/test-proj/.claude/agents/devops.md"
}

test_pack_rules_copied_to_project_claude() {
    # Rules defined in pack are copied to projects/<n>/.claude/rules/
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_dir="$tmpdir/global/packs/rules-pack"
    mkdir -p "$pack_dir/rules"
    echo "API rules" > "$pack_dir/rules/api-conventions.md"
    printf 'name: rules-pack\nrules:\n  - api-conventions.md\n' > "$pack_dir/pack.yml"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - rules-pack
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_file_exists "$CCO_PROJECTS_DIR/test-proj/.claude/rules/api-conventions.md"
}

# ── pack manifest (stale file cleanup) ──────────────────────────────

test_pack_manifest_created_after_copy() {
    # .pack-manifest is created listing all copied resources
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_dir="$tmpdir/global/packs/mf-pack"
    mkdir -p "$pack_dir/agents" "$pack_dir/rules"
    echo "Agent" > "$pack_dir/agents/bot.md"
    echo "Rule" > "$pack_dir/rules/style.md"
    printf 'name: mf-pack\nagents:\n  - bot.md\nrules:\n  - style.md\n' > "$pack_dir/pack.yml"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - mf-pack
YAML
)"
    run_cco start "test-proj" --dry-run
    local manifest="$CCO_PROJECTS_DIR/test-proj/.claude/.pack-manifest"
    assert_file_exists "$manifest"
    assert_file_contains "$manifest" "agents/bot.md"
    assert_file_contains "$manifest" "rules/style.md"
}

test_pack_manifest_stale_files_cleaned() {
    # When a pack removes a resource, the stale file is cleaned on next start
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_dir="$tmpdir/global/packs/evolve-pack"
    mkdir -p "$pack_dir/agents"
    echo "Agent v1" > "$pack_dir/agents/old-agent.md"
    echo "Agent v1" > "$pack_dir/agents/keep-agent.md"
    printf 'name: evolve-pack\nagents:\n  - old-agent.md\n  - keep-agent.md\n' > "$pack_dir/pack.yml"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - evolve-pack
YAML
)"
    # First start: both agents copied
    run_cco start "test-proj" --dry-run
    assert_file_exists "$CCO_PROJECTS_DIR/test-proj/.claude/agents/old-agent.md"
    assert_file_exists "$CCO_PROJECTS_DIR/test-proj/.claude/agents/keep-agent.md"
    # Remove old-agent from pack definition
    printf 'name: evolve-pack\nagents:\n  - keep-agent.md\n' > "$pack_dir/pack.yml"
    # Second start: old-agent should be cleaned
    run_cco start "test-proj" --dry-run
    assert_file_not_exists "$CCO_PROJECTS_DIR/test-proj/.claude/agents/old-agent.md"
    assert_file_exists "$CCO_PROJECTS_DIR/test-proj/.claude/agents/keep-agent.md"
}

test_pack_manifest_no_packs_cleans_all() {
    # Removing all packs from project.yml cleans previously copied resources
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_dir="$tmpdir/global/packs/temp-pack"
    mkdir -p "$pack_dir/rules"
    echo "Rule" > "$pack_dir/rules/temp-rule.md"
    printf 'name: temp-pack\nrules:\n  - temp-rule.md\n' > "$pack_dir/pack.yml"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - temp-pack
YAML
)"
    # First start: rule copied
    run_cco start "test-proj" --dry-run
    assert_file_exists "$CCO_PROJECTS_DIR/test-proj/.claude/rules/temp-rule.md"
    # Remove packs entirely
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
YAML
)"
    # Second start: stale rule should be cleaned
    run_cco start "test-proj" --dry-run
    assert_file_not_exists "$CCO_PROJECTS_DIR/test-proj/.claude/rules/temp-rule.md"
}

# ── pack name conflict warnings ──────────────────────────────────────

test_pack_conflict_warns_duplicate_agent() {
    # Two packs defining the same agent filename should emit a warning
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_a="$tmpdir/global/packs/pack-a"
    local pack_b="$tmpdir/global/packs/pack-b"
    mkdir -p "$pack_a/agents" "$pack_b/agents"
    echo "Agent from A" > "$pack_a/agents/reviewer.md"
    echo "Agent from B" > "$pack_b/agents/reviewer.md"
    printf 'name: pack-a\nagents:\n  - reviewer.md\n' > "$pack_a/pack.yml"
    printf 'name: pack-b\nagents:\n  - reviewer.md\n' > "$pack_b/pack.yml"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - pack-a
  - pack-b
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_output_contains "Agent 'reviewer.md' defined in both pack 'pack-a' and 'pack-b'"
}

test_pack_conflict_warns_duplicate_rule() {
    # Two packs defining the same rule filename should emit a warning
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_a="$tmpdir/global/packs/pack-a"
    local pack_b="$tmpdir/global/packs/pack-b"
    mkdir -p "$pack_a/rules" "$pack_b/rules"
    echo "Rule from A" > "$pack_a/rules/style.md"
    echo "Rule from B" > "$pack_b/rules/style.md"
    printf 'name: pack-a\nrules:\n  - style.md\n' > "$pack_a/pack.yml"
    printf 'name: pack-b\nrules:\n  - style.md\n' > "$pack_b/pack.yml"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - pack-a
  - pack-b
YAML
)"
    run_cco start "test-proj" --dry-run
    assert_output_contains "Rule 'style.md' defined in both pack 'pack-a' and 'pack-b'"
}

test_pack_no_conflict_unique_names() {
    # Packs with unique resource names should produce no warnings
    local tmpdir; tmpdir=$(mktemp -d); trap "rm -rf '$tmpdir'" EXIT
    setup_cco_env "$tmpdir"
    setup_global_from_defaults "$tmpdir"
    local pack_a="$tmpdir/global/packs/pack-a"
    local pack_b="$tmpdir/global/packs/pack-b"
    mkdir -p "$pack_a/agents" "$pack_b/agents"
    echo "Agent A" > "$pack_a/agents/analyst.md"
    echo "Agent B" > "$pack_b/agents/reviewer.md"
    printf 'name: pack-a\nagents:\n  - analyst.md\n' > "$pack_a/pack.yml"
    printf 'name: pack-b\nagents:\n  - reviewer.md\n' > "$pack_b/pack.yml"
    create_project "$tmpdir" "test-proj" "$(cat <<'YAML'
name: test-proj
auth:
  method: oauth
docker:
  ports: []
  env: {}
repos: []
packs:
  - pack-a
  - pack-b
YAML
)"
    run_cco start "test-proj" --dry-run
    # Should NOT contain any conflict warning
    if echo "$CCO_OUTPUT" | grep -q "defined in both pack"; then
        echo "ASSERTION FAILED: Expected no conflict warning but found one"
        echo "$CCO_OUTPUT" | grep "defined in both pack" | sed 's/^/    /'
        return 1
    fi
}
