#!/usr/bin/env bash
# Migration: Move browser runtime files to .managed/ directory
#
# Renames legacy files in the project root to the new .managed/ convention:
#   browser-mcp.json  →  .managed/browser.json
#   .browser-port     →  .managed/.browser-port
#
# Also adds .managed/ to project .gitignore (if present).

MIGRATION_ID=3
MIGRATION_DESC="Move browser files to .managed/ directory"

# $1 = target directory (e.g. projects/myapp)
# Must be idempotent (safe to run multiple times)
# Return 0 on success, non-zero on failure
migrate() {
    local target_dir="$1"

    # Move browser-mcp.json → .managed/browser.json
    if [[ -f "$target_dir/browser-mcp.json" ]] && [[ ! -f "$target_dir/.managed/browser.json" ]]; then
        mkdir -p "$target_dir/.managed"
        mv "$target_dir/browser-mcp.json" "$target_dir/.managed/browser.json"
    fi

    # Move .browser-port → .managed/.browser-port
    if [[ -f "$target_dir/.browser-port" ]] && [[ ! -f "$target_dir/.managed/.browser-port" ]]; then
        mkdir -p "$target_dir/.managed"
        mv "$target_dir/.browser-port" "$target_dir/.managed/.browser-port"
    fi

    # Add .managed/ to .gitignore if the file exists and the entry is absent
    local gitignore="$target_dir/.gitignore"
    if [[ -f "$gitignore" ]]; then
        if ! grep -qxF ".managed/" "$gitignore" 2>/dev/null; then
            printf '\n# Framework-managed integrations (auto-generated by cco start)\n.managed/\n' >> "$gitignore"
        fi
    fi

    return 0
}
