#!/usr/bin/env bash
# Migration: Initialize .cco-base for pre-Sprint-5b projects
#
# Projects created before Sprint 5b have no .cco-base/ directory.
# (They may or may not have .cco-meta, depending on whether cco update
# was run before.) Without .cco-base/, the 3-way merge falls back to
# interactive mode. This migration creates .cco-base/ retroactively so
# subsequent updates can auto-merge.

MIGRATION_ID=7
MIGRATION_DESC="Initialize .cco-base for 3-way merge support"

# $1 = target directory (e.g. projects/myapp)
# Must be idempotent (safe to run multiple times)
# Return 0 on success, non-zero on failure
migrate() {
    local target_dir="$1"
    local installed_dir="$target_dir/.claude"
    local defaults_dir="$NATIVE_TEMPLATES_DIR/project/base/.claude"

    # If no .claude/ dir, nothing to bootstrap
    [[ -d "$installed_dir" ]] || return 0

    # Post-consolidation path (.cco/base/) takes priority
    [[ -d "$target_dir/.cco/base" ]] && return 0
    # Pre-consolidation path (.cco-base/)
    [[ -d "$target_dir/.cco-base" ]] && return 0

    # Create at .cco/base/ if .cco/ exists (post-009), else .cco-base/ (pre-009)
    local base_dir="$target_dir/.cco-base"
    if [[ -d "$target_dir/.cco" ]]; then
        base_dir="$target_dir/.cco/base"
    fi
    _save_all_base_versions "$base_dir" "$defaults_dir" "project"

    # .cco-meta is generated by _update_project after migrations run,
    # so we don't need to create it here — it will be written automatically.

    return 0
}
