#!/usr/bin/env bash
# lib/cmd-clean.sh — Clean up files created by cco update, start, and dry-run
#
# Provides: cmd_clean()
# Dependencies: colors.sh, utils.sh
# Globals: GLOBAL_DIR, PROJECTS_DIR

cmd_clean() {
    local dry_run=false
    local project=""
    local clean_all=false
    local cat_bak=false
    local cat_new=false
    local cat_tmp=false
    local cat_generated=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --project)
                [[ -z "${2:-}" ]] && die "--project requires a project name"
                project="$2"; shift 2 ;;
            --bak)        cat_bak=true; shift ;;
            --new)        cat_new=true; shift ;;
            --tmp)        cat_tmp=true; shift ;;
            --generated)  cat_generated=true; shift ;;
            --all)        clean_all=true; shift ;;
            --dry-run)    dry_run=true; shift ;;
            --help)
                cat <<'EOF'
Usage: cco clean [OPTIONS]

Remove files created by 'cco update', 'cco start', and dry-run operations.

Categories:
  (default)        Remove .bak files created by update merges
  --bak            Explicitly select .bak category (same as default)
  --new            Remove .new files created by update sync (New-file option)
  --tmp            Remove .tmp/ directories (dry-run artifacts)
  --generated      Remove docker-compose.yml (regenerated by cco start)
  --all            Run all categories (bak + new + tmp + generated)

Scoping:
  --project <name> Clean only a specific project
  (no --project)   Clean global + all projects

Other:
  --dry-run        Show what would be removed without deleting
  --help           Show this help message

Examples:
  cco clean                          # Remove .bak files (global + all projects)
  cco clean --dry-run                # Preview what would be removed
  cco clean --project myapp          # Clean .bak in specific project only
  cco clean --tmp                    # Remove .tmp/ dirs from all projects
  cco clean --generated              # Remove docker-compose.yml from all projects
  cco clean --all                    # All categories, global + all projects
  cco clean --all --project myapp    # All categories, single project
EOF
                return 0
                ;;
            *) die "Unknown option: $1. Run 'cco clean --help' for usage." ;;
        esac
    done

    check_global

    # If --all is set, enable all categories
    if $clean_all; then
        cat_bak=true
        cat_new=true
        cat_tmp=true
        cat_generated=true
    fi

    # Default: if no category explicitly selected, clean .bak
    if ! $cat_bak && ! $cat_new && ! $cat_tmp && ! $cat_generated; then
        cat_bak=true
    fi

    local total_bak=0
    local total_new=0
    local total_tmp=0
    local total_generated=0

    if [[ -n "$project" ]]; then
        # Scoped to a specific project
        local project_dir="$PROJECTS_DIR/$project"
        if [[ ! -d "$project_dir" ]]; then
            warn "Project '$project' not found."
            return 1
        fi

        if $cat_bak; then
            total_bak=$(_clean_bak "$project_dir" "$dry_run" "project/$project")
        fi
        if $cat_new; then
            total_new=$(_clean_new "$project_dir" "$dry_run" "project/$project")
        fi
        if $cat_tmp; then
            total_tmp=$(_clean_tmp "$project_dir" "$dry_run" "project/$project")
        fi
        if $cat_generated; then
            total_generated=$(_clean_generated "$project_dir" "$dry_run" "project/$project")
        fi
    else
        # Global + all projects
        if $cat_bak; then
            total_bak=$(_clean_bak "$GLOBAL_DIR" "$dry_run" "global")
        fi
        if $cat_new; then
            total_new=$(( total_new + $(_clean_new "$GLOBAL_DIR" "$dry_run" "global") ))
        fi

        local project_dir
        for project_dir in "$PROJECTS_DIR"/*/; do
            [[ ! -d "$project_dir" ]] && continue
            local pname
            pname="$(basename "$project_dir")"

            if $cat_bak; then
                local count
                count=$(_clean_bak "$project_dir" "$dry_run" "project/$pname")
                total_bak=$((total_bak + count))
            fi
            if $cat_new; then
                local count
                count=$(_clean_new "$project_dir" "$dry_run" "project/$pname")
                total_new=$((total_new + count))
            fi
            if $cat_tmp; then
                local count
                count=$(_clean_tmp "$project_dir" "$dry_run" "project/$pname")
                total_tmp=$((total_tmp + count))
            fi
            if $cat_generated; then
                local count
                count=$(_clean_generated "$project_dir" "$dry_run" "project/$pname")
                total_generated=$((total_generated + count))
            fi
        done
    fi

    # Summary
    local grand_total=$((total_bak + total_new + total_tmp + total_generated))

    if [[ $grand_total -eq 0 ]]; then
        info "Nothing to clean."
        return 0
    fi

    echo "" >&2
    if $dry_run; then
        [[ $total_bak -gt 0 ]] && info "Would remove $total_bak .bak file(s)."
        [[ $total_new -gt 0 ]] && info "Would remove $total_new .new file(s)."
        [[ $total_tmp -gt 0 ]] && info "Would remove $total_tmp .tmp/ directory(ies)."
        [[ $total_generated -gt 0 ]] && info "Would remove $total_generated docker-compose.yml file(s)."
        info "Run without --dry-run to delete."
    else
        [[ $total_bak -gt 0 ]] && ok "Removed $total_bak .bak file(s)."
        [[ $total_new -gt 0 ]] && ok "Removed $total_new .new file(s)."
        [[ $total_tmp -gt 0 ]] && ok "Removed $total_tmp .tmp/ directory(ies)."
        [[ $total_generated -gt 0 ]] && ok "Removed $total_generated docker-compose.yml file(s)."
    fi
}

# ── Category: .bak files ─────────────────────────────────────────────
# Find and remove .bak files in a directory tree.
# Usage: _clean_bak <dir> <dry_run> <label>
# Prints count to stdout. Messages go to stderr.
_clean_bak() {
    local dir="$1"
    local dry_run="$2"
    local label="$3"
    local count=0

    [[ ! -d "$dir" ]] && echo 0 && return 0

    while IFS= read -r -d '' bakfile; do
        count=$((count + 1))
        local rel="${bakfile#$dir/}"
        if [[ "$dry_run" == "true" ]]; then
            echo "  [dry-run] [$label] $rel" >&2
        else
            rm -f "$bakfile"
        fi
    done < <(find "$dir" -name '*.bak' -type f -print0 2>/dev/null)

    echo "$count"
}

# ── Category: .new files ─────────────────────────────────────────────
# Find and remove .new files in a directory tree (created by cco update --sync New-file option).
# Usage: _clean_new <dir> <dry_run> <label>
# Prints count to stdout. Messages go to stderr.
_clean_new() {
    local dir="$1"
    local dry_run="$2"
    local label="$3"
    local count=0

    [[ ! -d "$dir" ]] && echo 0 && return 0

    while IFS= read -r -d '' newfile; do
        count=$((count + 1))
        local rel="${newfile#$dir/}"
        if [[ "$dry_run" == "true" ]]; then
            echo "  [dry-run] [$label] $rel" >&2
        else
            rm -f "$newfile"
        fi
    done < <(find "$dir" -name '*.new' -type f -print0 2>/dev/null)

    echo "$count"
}

# ── Category: .tmp/ directories ──────────────────────────────────────
# Remove .tmp/ directory from a project dir (created by cco start --dry-run).
# Usage: _clean_tmp <project_dir> <dry_run> <label>
# Prints count (0 or 1) to stdout. Messages go to stderr.
_clean_tmp() {
    local dir="$1"
    local dry_run="$2"
    local label="$3"

    local tmp_dir="$dir/.tmp"
    if [[ -d "$tmp_dir" ]]; then
        if [[ "$dry_run" == "true" ]]; then
            echo "  [dry-run] [$label] .tmp/" >&2
        else
            rm -rf "$tmp_dir"
        fi
        echo 1
    else
        echo 0
    fi
}

# ── Category: docker-compose.yml (generated) ────────────────────────
# Remove docker-compose.yml from a project dir (regenerated by cco start).
# Usage: _clean_generated <project_dir> <dry_run> <label>
# Prints count (0 or 1) to stdout. Messages go to stderr.
_clean_generated() {
    local dir="$1"
    local dry_run="$2"
    local label="$3"

    local compose_file="$dir/.cco/docker-compose.yml"
    if [[ -f "$compose_file" ]]; then
        if [[ "$dry_run" == "true" ]]; then
            echo "  [dry-run] [$label] docker-compose.yml" >&2
        else
            rm -f "$compose_file"
        fi
        echo 1
    else
        echo 0
    fi
}
