#!/usr/bin/env bash
# lib/dev.sh — Developer execution mode: the CONFIGURATION protections (ADR-0060 §5)
#
# A10.1 forked the code IDENTITY (the image) and the internal buckets. This file is
# the other half of the mode: configuration is deliberately NOT forked — it is the
# test's INPUT, not its target (ADR-0060 D4) — so what dev mode owes the developer
# is not a different `~/.cco` but the SURVIVAL of a bad write to the real one.
#
#   ~/.cco          protected by an unconditional pre-run snapshot (§5)
#   <repo>/.cco     protected by the user's OWN repo git, and therefore by a GUARD
#                   that refuses a destructive writer when that git cannot help (§5.2)
#
# Provides:
#   Snapshot store: _cco_dev_snapshot_store, _cco_dev_snapshot_init,
#                   _cco_dev_snapshot, _cco_dev_snapshot_engage,
#                   _cco_dev_snapshot_has_commits, _dev_snap_git
#   Project guard:  _cco_dev_project_restorable, _cco_dev_project_guard,
#                   _cco_dev_project_guard_members, _cco_dev_project_guard_fanout
#   Migration route:_cco_dev_guard_config_migration
# Dependencies: colors.sh (note/die/refuse), paths.sh (_cco_dev_root/_cco_dev_active/
#   _cco_config_dir_path/_cco_config_isolated), secrets.sh (_SECRET_FILENAME_PATTERNS),
#   cmd-project-save.sh (_project_resolve_unit), utils.sh (_peel_tab),
#   index.sh (_project_iter_members), cmd-resolve.sh (_project_foreach),
#   rename.sh (_yaml_list_has_ref) — all resolved at call time
# Globals: none owned. _cco_dev_project_restorable calls _project_resolve_unit and so
#   sets its _PROJECT_{GITROOT,SPEC,REPO}; _cco_dev_project_guard asks it inside a
#   command substitution, so a guarded call site never has those clobbered under it.

# ── The snapshot store (ADR-0060 D4, design §5) ─────────────────────
#
# <dev-root>/snapshots/config.git, a SIBLING of the three redirected buckets and
# never a child of state/: `_cco_dev_sandbox_seed` does `cp -a "$real_state"
# "$root/state"` behind a one-shot `[[ -d "$root/state" ]]` guard, so a store under
# state/ would be indistinguishable from copied real STATE and entangled with that
# guard — either the seed could never run, or a re-seed would overwrite the store.
#
# NEVER `~/.cco/.git`. `cco config save`'s contract is explicit — "cco never
# auto-commits" — and an automatic commit into that history would both break it and
# pollute `cco config history`. Living under the dev root also makes the store
# STRUCTURALLY UNPUSHABLE: `_config_push` operates on `$cfg/.git` and cannot see it.
_cco_dev_snapshot_store() { printf '%s\n' "$(_cco_dev_root)/snapshots/config.git"; }

# Every git call against the store. The store is bare and the work tree is elsewhere,
# so BOTH must be named on every invocation — the dotfiles-repo shape.
# Usage: _dev_snap_git <store> <work-tree> <git args…>
_dev_snap_git() {
    local store="$1" wt="$2"
    shift 2
    git --git-dir="$store" --work-tree="$wt" "$@"
}

# True (0) when the store holds at least one snapshot.
_cco_dev_snapshot_has_commits() {
    local store="$1"
    [[ -d "$store" ]] || return 1
    git --git-dir="$store" rev-parse --verify -q HEAD >/dev/null 2>&1
}

# $GIT_DIR/info/exclude — the secret classes `lib/secrets.sh` already matches,
# REUSED rather than restated, plus `.git/` so the user's own ~/.cco config repo is
# not recorded as a gitlink. Reusing the canonical array excludes a superset of the
# four the design enumerates (it also carries `.credentials.json`, `.netrc` and
# `.cco/remotes`) — every member is a secret class, and D4.5's property is that NO
# secret material is duplicated to a second location on disk.
#
# ⚠ One semantic bridge: `_secret_match_filename` matches a pattern as a BASENAME or
# a path SUFFIX at any depth, while a gitignore pattern CONTAINING a slash is
# anchored to the work-tree root. `**/` restores the any-depth reading for those.
_cco_dev_snapshot_write_exclude() {
    local store="$1" p
    local info="$store/info"      # separate statement: `local` expands all its args first
    ( umask 077; mkdir -p "$info" ) || return 1
    {
        printf '# Generated by cco — dev-mode snapshot exclusions (ADR-0060 D4.5).\n'
        printf '# The secret classes lib/secrets.sh matches, reused not restated.\n'
        for p in ${_SECRET_FILENAME_PATTERNS[@]+"${_SECRET_FILENAME_PATTERNS[@]}"}; do
            case "$p" in
                */*) printf '**/%s\n' "$p" ;;
                *)   printf '%s\n' "$p" ;;
            esac
        done
        printf '.git/\n'
    } > "$info/exclude" || return 1
}

# Create the store if it is absent and (re)write its exclusions.
#
# 🔴 ORDERING IS LOAD-BEARING AND GETTING IT WRONG IS A FALSE PASS: info/exclude is
# written HERE, at init, BEFORE the first `git add -A` — a store whose FIRST commit
# already contained `secrets.env` would still satisfy a test that only asserts the
# exclusions exist. Rewriting on every init keeps it true after a `_SECRET_*` change
# and stays ahead of every add.
#
# The identity and gpgsign settings are LOCAL to the store and written only at
# creation: this is a safety store, not a publication, so it must commit on a machine
# whose git has no user.email and whose global config signs every commit.
_cco_dev_snapshot_init() {
    local store="$1" wt="$2"
    if [[ ! -d "$store" ]]; then
        ( umask 077; mkdir -p "$store" ) \
            || die "dev snapshot: could not create the snapshot store at $store."
        git init -q --bare "$store" \
            || die "dev snapshot: 'git init' failed for the snapshot store at $store."
        git --git-dir="$store" config user.name  "cco dev snapshot" \
            || die "dev snapshot: could not configure the snapshot store at $store."
        git --git-dir="$store" config user.email "cco-dev@localhost" \
            || die "dev snapshot: could not configure the snapshot store at $store."
        git --git-dir="$store" config commit.gpgsign false \
            || die "dev snapshot: could not configure the snapshot store at $store."
    fi
    _cco_dev_snapshot_write_exclude "$store" \
        || die "dev snapshot: could not write the secret exclusions into $store/info/exclude — refusing to snapshot $wt without them."
}

# Take one snapshot of the real ~/.cco. The three rows of design §5.0b, in order:
#
#   ~/.cco absent                     → no-op + note  (nothing to protect; NOT a failure)
#   ~/.cco present, anything fails    → die           (ruled by the maintainer 2026-09-01)
#   ~/.cco present, tree unchanged    → no commit, no message (the step SUCCEEDED)
#
# 🔴 Why `die` and not `warn`: this deliberately departs from `_cco_dev_sandbox_seed`,
# and the distinction is the point — a partial seed is a convenience, a missing
# restore point IS the protection. If it cannot be taken, the mode's safety property
# could not be established and the run must not proceed.
#
# Plain `git` only, NEVER through `cco config save`: that verb may itself be the code
# under test, and it is allowlisted (it omits access.yml and claude-version, the two
# members with no other recovery path) where a safety snapshot wants `git add -A`.
# Usage: _cco_dev_snapshot <argv…>   (the verb line this snapshot precedes)
_cco_dev_snapshot() {
    local cfg store dirty
    cfg=$(_cco_config_dir_path)
    if [[ ! -d "$cfg" ]]; then
        note "dev snapshot: $cfg does not exist yet — there is nothing to protect, so no snapshot was taken"
        return 0
    fi
    store=$(_cco_dev_snapshot_store)
    _cco_dev_snapshot_init "$store" "$cfg"

    # ⚠ `add -A` BEFORE `status --porcelain`, and the order is load-bearing: it
    # re-syncs the index from the work tree, so `status` answers "does the work tree
    # differ from the last snapshot" rather than "does a possibly stale index".
    # Asking `status` first would let an index left pointing elsewhere (as a restore
    # does) report changes the commit then finds empty — and an empty commit returns
    # non-zero, which D4.4 turns into a die. A recovery path that bricks the next run.
    _dev_snap_git "$store" "$cfg" add -A \
        || die "dev snapshot: could not stage $cfg into $store. Dev mode cannot establish a restore point, so it will not run the verb. Fix the store (or remove $store to start a fresh one) and retry."
    dirty=$(_dev_snap_git "$store" "$cfg" status --porcelain 2>/dev/null) \
        || die "dev snapshot: 'git status' failed against $store. Dev mode cannot tell whether $cfg changed, so it will not run the verb."
    # An empty commit records nothing — the step succeeded, silently.
    [[ -n "$dirty" ]] || return 0
    _dev_snap_git "$store" "$cfg" commit -q -m "dev snapshot before: cco $*" \
        || die "dev snapshot: could not commit $cfg into $store. Dev mode has no restore point for this run, so it will not run the verb."
}

# The engage-time call, from bin/cco. 🔴 THE STEP IS UNCONDITIONAL: it runs at every
# `cco --dev` engage, before the verb, WHATEVER the verb is. It is never keyed on a
# list of config-writing verbs — a named list is a lower bound, a class this repo has
# paid for four times.
_cco_dev_snapshot_engage() {
    _cco_dev_active || return 0
    _cco_dev_snapshot "$@"
}

# ── The <repo>/.cco restorability guard (ADR-0060 D4.8, design §5.2) ─
#
# The snapshot's work tree is `~/.cco` ALONE. Project config is protected by the
# user's own repo git, and that protection is complete only when the tree is
# versioned and clean. Three cases it does not cover — uncommitted changes, a
# never-committed or gitignored `.cco`, and a repo that is not git at all (a
# supported case) — and the instrument for all three is a refusal, not a second store:
# project config has no choke point, so a store would be anchored on the same list a
# guard is, while adding a per-project reaper.
#
# ⭐ THE MEMBERSHIP CRITERION IS THE RULING, NOT THE LIST: the guard applies to a
# writer that can DESTROY UNCOMMITTED CONTENT. A writer whose only effect is a COMMIT
# is exempt — a commit is revertable by construction. That exempts `cco project save`,
# and the exemption is required rather than cosmetic: it only does anything when
# `.cco` is dirty, so a dirty-check would make it permanently untestable in dev mode.
# Classify a future writer by the criterion, never by finding it on a list.
#
# 🔴 NEVER `git -C <unit-dir> … -- .cco`. Every git OUTPUT path (`status --porcelain`,
# `ls-files`, `diff --cached --name-only`, `check-ignore -v`'s source) is reported
# relative to the TOP LEVEL, never to cwd. Joining those onto a unit dir failed
# silently and a secret under a nested `.cco/` was committed under "✓ saved". Both
# halves below anchor on `_project_resolve_unit`'s $_PROJECT_GITROOT + $_PROJECT_SPEC.
#
# Echoes the REASON on failure (one line, nothing on success) so the caller renders
# which of the three conditions fired. ⚠ Every reason names the ABSOLUTE path it
# judged — `$_PROJECT_GITROOT/$_PROJECT_SPEC`, never the `<repo>/.cco` display form
# `cmd-project-save.sh` prints: a refusal is read outside the directory it is about,
# and a bare basename does not tell the reader WHICH repo to go and commit.
# Usage: _cco_dev_project_restorable <unit_dir>
_cco_dev_project_restorable() {
    local unit="$1" dirty
    # 1. Not a git work tree — a supported case, and one with no protection at all.
    if ! _project_resolve_unit "$unit"; then
        printf 'the repo holding it (%s) is not a git work tree, so there is nothing to restore to\n' "$unit"
        return 1
    fi
    # 2. Nothing tracked — never committed, or gitignored.
    #
    # ⚠ ORDER 2 BEFORE 3, AND KEEP BOTH. An entirely untracked `.cco` ALSO shows in
    # `status --porcelain` (as `??`), so asking 3 first would blame "uncommitted
    # changes" for what is really "never committed". And a GITIGNORED `.cco` shows in
    # neither `status` (ignored files are hidden) nor `ls-files` — 2 is what catches
    # it. Either check alone leaves a hole.
    if ! git -C "$_PROJECT_GITROOT" ls-files --error-unmatch -- "$_PROJECT_SPEC" >/dev/null 2>&1; then
        printf '%s/%s is not tracked by git — never committed, or gitignored\n' "$_PROJECT_GITROOT" "$_PROJECT_SPEC"
        return 1
    fi
    # 3. Tracked, but dirty — the delta is what would be lost.
    dirty=$(git -C "$_PROJECT_GITROOT" status --porcelain -- "$_PROJECT_SPEC" 2>/dev/null) || dirty=""
    if [[ -n "$dirty" ]]; then
        printf '%s/%s has uncommitted changes\n' "$_PROJECT_GITROOT" "$_PROJECT_SPEC"
        return 1
    fi
    return 0
}

# The call every guarded writer makes. A strict no-op outside dev mode — which is what
# keeps the ordinary path byte-identical and the guard's false arm exercised by every
# non-dev run of the suite.
#
# 📝 No escape flag. Round 3 dropped `--allow-project-writes` and this does not bring
# it back: a throwaway git repo is the escape. Reopen only if the refusal is measured
# to block a real workflow.
# Usage: _cco_dev_project_guard <unit_dir> <verb label>
_cco_dev_project_guard() {
    local unit="$1" verb="$2" why
    _cco_dev_active || return 0
    [[ -n "$unit" ]] || return 0
    # Asked inside a command substitution on purpose: _project_resolve_unit's globals
    # then die with the subshell instead of being clobbered under the caller.
    why=$(_cco_dev_project_restorable "$unit") && return 0
    refuse "dev mode: refusing '$verb' — it can destroy uncommitted content under <repo>/.cco, and $why. Dev mode snapshots ~/.cco only; your project config is protected by your own repo git (ADR-0060 D4.8). Two ways out: commit or stash .cco/ in that repo, or work on a fixture project — a throwaway git repo whose .cco/ is committed, which 'cco dev project new' creates by construction (it lands with A10.2 wave 2)."
}

# Guard every RESOLVED member of <project>, in the PARENT shell.
#
# ⚠ Why here and not inside the writer: both project.yml fan-outs
# (`_rename_projectyml_current`, `_rename_fanout_projectyml`) are consumed through a
# PROCESS SUBSTITUTION, where a `refuse` would exit only the subshell and the verb
# would sail on. A `while … done < <(…)` body runs in the parent, so this pre-flight
# refuses for real — the same fail-closed shape `_rename_assert_writable` already
# uses, and for the same reason: a fan-out either wholly applies or wholly refuses.
# Usage: _cco_dev_project_guard_members <project> <verb label>
_cco_dev_project_guard_members() {
    local project="$1" verb="$2" _ln name path status
    _cco_dev_active || return 0
    while IFS= read -r _ln; do
        [[ -z "$_ln" ]] && continue
        # Column 2 is EMPTY for an unresolved member and tab is IFS whitespace, so
        # `IFS=$'\t' read` would fold the gap and mis-assign; peel by hand.
        _peel_tab "$_ln" name path status
        case "$status" in synced|divergent) ;; *) continue ;; esac
        [[ -n "$path" ]] || continue
        _cco_dev_project_guard "$path" "$verb"
    done < <(_project_iter_members "$project")
}

# The cross-project variant: for every project whose primary project.yml references
# <old> in <section>, guard its own unit dir AND every resolved member. Two writers
# share it and each touches one of those halves — `cco llms rename` rewrites the
# PRIMARY project.yml (`_project_foreach`), `cco pack rename` fans out over the
# MEMBERS (`_rename_fanout_projectyml`) — so the union is the honest pre-flight.
# ⚠ Accepted cost, stated rather than hidden: for the primary-only writer the member
# half is a superset, so a dirty member repo can refuse a rename that would not have
# touched it. The remedy is the same (commit it), and a guard that under-covers a
# fan-out is the failure that actually loses work.
# Usage: _cco_dev_project_guard_fanout <section> <old> <verb label>
_cco_dev_project_guard_fanout() {
    local section="$1" old="$2" verb="$3" proj unit yml
    _cco_dev_active || return 0
    while IFS=$'\t' read -r proj unit yml; do
        [[ -n "$yml" ]] || continue
        _yaml_list_has_ref "$yml" "$section" "$old" || continue
        [[ -n "$unit" ]] && _cco_dev_project_guard "$unit" "$verb"
        _cco_dev_project_guard_members "$proj" "$verb"
    done < <(_project_foreach)
}

# ── Migration routing (ADR-0060 D5) ─────────────────────────────────
#
# With CONFIG shared and STATE sandboxed, `_run_migrations` would run target-shared /
# marker-sandboxed: a dev-run migration mutates the real ~/.cco/.claude and records
# that it ran in a bucket the published binary never reads, so the published binary
# RUNS IT AGAIN. A restore puts the files back and leaves the bookkeeping wrong — the
# one class the snapshot cannot repair, which is why this refuses instead.
# Usage: _cco_dev_guard_config_migration <scope label> <target dir>
_cco_dev_guard_config_migration() {
    local scope="$1" target="$2"
    _cco_dev_active || return 0
    _cco_config_isolated && return 0
    refuse "dev mode: refusing to run $scope migrations against $target. Configuration is SHARED with your real cco (ADR-0060 D4), but the schema marker that records a migration as done is not — it lives in the sandboxed buckets, so your published cco would run the same migration a second time, and the snapshot cannot repair that bookkeeping. Point cco at an isolated config first: CCO_CONFIG_HOME=<dir> cco --dev <verb>."
}

# The same ruling at `cco init`'s global seed — a SEPARATE entry point because the
# refusal is placed where the seed DECIDES TO WRITE, never at its `_run_migrations`
# call, and because it names a second way out the migration one cannot.
#
# 🔴 PLACEMENT, measured (2026-09-03): `_cco_init_ensure_global` does
# `rm -rf "$gclaude"` on --force some seventy lines ABOVE its `_run_migrations`
# call. A refusal at the call site would therefore fire AFTER the user's real global
# config had already been deleted — a guard that destroys the thing it exists to
# protect. It goes ahead of the delete, at the point the function commits to writing.
#
# ⭐ BOTH flows refuse — fresh seed and --force alike (maintainer's ruling
# 2026-09-03) — and the fresh one is the WORSE divergence, which inverts the
# intuitive reading: `_cco_global_meta` resolves under `_cco_state_dir`, which
# `--dev` SANDBOXES. So a fresh dev init would create the config in the real, shared
# ~/.cco while recording "schema current" only in the sandbox; the published binary
# would then see schema 0 against an already-current config and re-run the entire
# migration chain over it. Exempting the fresh case was rejected on that evidence.
#
# 📝 Accepted and stated rather than hidden: DEV MODE CANNOT BOOTSTRAP A MACHINE.
# Usage: _cco_dev_guard_config_init <target dir>
_cco_dev_guard_config_init() {
    local target="$1"
    _cco_dev_active || return 0
    _cco_config_isolated && return 0
    refuse "dev mode cannot bootstrap a machine: refusing to seed the global config at $target. Configuration is SHARED with your real cco (ADR-0060 D4), but the schema marker that records the seed as current is not — it lives in the sandboxed dev buckets, so your published cco would see an already-current config at schema 0 and re-run the whole migration chain over it. Two ways out: run 'cco init' WITHOUT --dev (bootstrapping a real machine is a one-time act and belongs to the real binary), or point cco at a throwaway config — CCO_CONFIG_HOME=<dir> cco --dev init (a 'cco dev config new' helper lands with A10.2 wave 2)."
}
