#!/usr/bin/env bash
# lib/manifest.sh — manifest.yml lifecycle management
#
# Provides: manifest_init(), manifest_refresh(), manifest_validate(), manifest_show(),
#           cmd_manifest()
# Dependencies: colors.sh, utils.sh, yaml.sh
# Globals: USER_CONFIG_DIR, PACKS_DIR, TEMPLATES_DIR

# ── manifest.yml generation ──────────────────────────────────────────

# Initialize a minimal manifest.yml in the given config directory.
# Usage: manifest_init "$USER_CONFIG_DIR"
manifest_init() {
    local config_dir="$1"
    local manifest_file="$config_dir/manifest.yml"

    # Backward compat: adopt existing share.yml if manifest.yml doesn't exist
    if [[ ! -f "$manifest_file" && -f "$config_dir/share.yml" ]]; then
        mv "$config_dir/share.yml" "$manifest_file"
        return 0
    fi

    if [[ -f "$manifest_file" ]]; then
        return 0
    fi

    cat > "$manifest_file" <<'YAML'
# Auto-generated by cco — edit name, description, and tags as needed
name: ""
description: ""

packs: []

templates: []
YAML
}

# Regenerate manifest.yml by scanning packs/ and templates/ directories.
# Preserves user-edited name, description, and per-entry descriptions/tags.
# Usage: manifest_refresh "$USER_CONFIG_DIR"
manifest_refresh() {
    local config_dir="$1"
    local manifest_file="$config_dir/manifest.yml"
    local packs_dir="$config_dir/packs"
    local templates_dir="$config_dir/templates"

    # Backward compat: adopt existing share.yml
    if [[ ! -f "$manifest_file" && -f "$config_dir/share.yml" ]]; then
        mv "$config_dir/share.yml" "$manifest_file"
    fi

    # Read existing name/description if manifest.yml already exists
    local repo_name="" repo_desc=""
    if [[ -f "$manifest_file" ]]; then
        repo_name=$(yml_get "$manifest_file" "name")
        repo_desc=$(yml_get "$manifest_file" "description")
    fi

    # Collect existing per-pack descriptions and tags from current manifest.yml
    # We store them in associative-style temp files for lookup
    local existing_meta=""
    if [[ -f "$manifest_file" ]]; then
        existing_meta=$(_manifest_read_pack_meta "$manifest_file")
    fi
    local existing_tmpl_meta=""
    if [[ -f "$manifest_file" ]]; then
        existing_tmpl_meta=$(_manifest_read_template_meta "$manifest_file")
    fi

    # Scan packs directory
    local -a pack_entries=()
    if [[ -d "$packs_dir" ]]; then
        for dir in "$packs_dir"/*/; do
            [[ ! -d "$dir" ]] && continue
            local name
            name=$(basename "$dir")
            local pack_yml="$dir/pack.yml"

            # Get description from pack.yml, or from existing manifest.yml
            local desc=""
            if [[ -f "$pack_yml" ]]; then
                desc=$(yml_get "$pack_yml" "description")
            fi
            if [[ -z "$desc" ]]; then
                desc=$(_manifest_lookup_meta "$existing_meta" "$name" "description")
            fi

            # Get tags from existing manifest.yml (not in pack.yml)
            local tags
            tags=$(_manifest_lookup_meta "$existing_meta" "$name" "tags")

            pack_entries+=("$name|$desc|$tags")
        done
    fi

    # Scan templates directory
    local -a tmpl_entries=()
    if [[ -d "$templates_dir" ]]; then
        for dir in "$templates_dir"/*/; do
            [[ ! -d "$dir" ]] && continue
            local name
            name=$(basename "$dir")

            local desc=""
            desc=$(_manifest_lookup_meta "$existing_tmpl_meta" "$name" "description")

            local tags
            tags=$(_manifest_lookup_meta "$existing_tmpl_meta" "$name" "tags")

            tmpl_entries+=("$name|$desc|$tags")
        done
    fi

    # Write manifest.yml
    {
        echo "# Auto-generated by cco — edit name, description, and tags as needed"
        echo "name: \"${repo_name}\""
        echo "description: \"${repo_desc}\""
        echo ""

        if [[ ${#pack_entries[@]} -eq 0 ]]; then
            echo "packs: []"
        else
            echo "packs:"
            for entry in "${pack_entries[@]}"; do
                IFS='|' read -r name desc tags <<< "$entry"
                echo "  - name: $name"
                if [[ -n "$desc" ]]; then
                    echo "    description: \"$desc\""
                fi
                if [[ -n "$tags" ]]; then
                    echo "    tags: [$tags]"
                fi
            done
        fi

        echo ""

        if [[ ${#tmpl_entries[@]} -eq 0 ]]; then
            echo "templates: []"
        else
            echo "templates:"
            for entry in "${tmpl_entries[@]}"; do
                IFS='|' read -r name desc tags <<< "$entry"
                echo "  - name: $name"
                if [[ -n "$desc" ]]; then
                    echo "    description: \"$desc\""
                fi
                if [[ -n "$tags" ]]; then
                    echo "    tags: [$tags]"
                fi
            done
        fi
    } > "$manifest_file"
}

# Validate manifest.yml against disk contents.
# Returns 0 if valid, 1 if issues found.
# Usage: manifest_validate "$USER_CONFIG_DIR"
manifest_validate() {
    local config_dir="$1"
    local manifest_file="$config_dir/manifest.yml"
    local has_issues=false

    # Backward compat: adopt existing share.yml
    if [[ ! -f "$manifest_file" && -f "$config_dir/share.yml" ]]; then
        mv "$config_dir/share.yml" "$manifest_file"
    fi

    if [[ ! -f "$manifest_file" ]]; then
        warn "manifest.yml not found at $manifest_file"
        return 1
    fi

    # Check packs listed in manifest.yml exist on disk
    local manifest_packs
    manifest_packs=$(_manifest_get_names "$manifest_file" "packs")
    while IFS= read -r name; do
        [[ -z "$name" ]] && continue
        if [[ ! -d "$config_dir/packs/$name" ]]; then
            warn "manifest.yml lists pack '$name' but packs/$name/ does not exist (stale entry)"
            has_issues=true
        fi
    done <<< "$manifest_packs"

    # Check packs on disk are listed in manifest.yml
    if [[ -d "$config_dir/packs" ]]; then
        for dir in "$config_dir/packs"/*/; do
            [[ ! -d "$dir" ]] && continue
            local name
            name=$(basename "$dir")
            if ! echo "$manifest_packs" | grep -qxF "$name"; then
                warn "packs/$name/ exists but is not listed in manifest.yml (missing entry)"
                has_issues=true
            fi
        done
    fi

    # Check templates listed in manifest.yml exist on disk
    local manifest_templates
    manifest_templates=$(_manifest_get_names "$manifest_file" "templates")
    while IFS= read -r name; do
        [[ -z "$name" ]] && continue
        if [[ ! -d "$config_dir/templates/$name" ]]; then
            warn "manifest.yml lists template '$name' but templates/$name/ does not exist (stale entry)"
            has_issues=true
        fi
    done <<< "$manifest_templates"

    # Check templates on disk are listed in manifest.yml
    if [[ -d "$config_dir/templates" ]]; then
        for dir in "$config_dir/templates"/*/; do
            [[ ! -d "$dir" ]] && continue
            local name
            name=$(basename "$dir")
            if ! echo "$manifest_templates" | grep -qxF "$name"; then
                warn "templates/$name/ exists but is not listed in manifest.yml (missing entry)"
                has_issues=true
            fi
        done
    fi

    if [[ "$has_issues" == true ]]; then
        info "Run 'cco manifest refresh' to fix manifest.yml"
        return 1
    fi

    ok "manifest.yml is valid"
    return 0
}

# Display manifest.yml contents in a formatted way.
# Usage: manifest_show "$USER_CONFIG_DIR"
manifest_show() {
    local config_dir="$1"
    local manifest_file="$config_dir/manifest.yml"

    # Backward compat: adopt existing share.yml
    if [[ ! -f "$manifest_file" && -f "$config_dir/share.yml" ]]; then
        mv "$config_dir/share.yml" "$manifest_file"
    fi

    if [[ ! -f "$manifest_file" ]]; then
        die "manifest.yml not found. Run 'cco init' or 'cco manifest refresh' first."
    fi

    local repo_name repo_desc
    repo_name=$(yml_get "$manifest_file" "name")
    repo_desc=$(yml_get "$manifest_file" "description")

    echo -e "${BOLD}Config Repo${NC}"
    if [[ -n "$repo_name" ]]; then
        echo "  Name: $repo_name"
    fi
    if [[ -n "$repo_desc" ]]; then
        echo "  Description: $repo_desc"
    fi
    echo ""

    echo -e "${BOLD}Packs:${NC}"
    local manifest_packs
    manifest_packs=$(_manifest_get_names "$manifest_file" "packs")
    if [[ -z "$manifest_packs" ]]; then
        echo "  (none)"
    else
        while IFS= read -r name; do
            [[ -z "$name" ]] && continue
            echo "  - $name"
        done <<< "$manifest_packs"
    fi
    echo ""

    echo -e "${BOLD}Templates:${NC}"
    local manifest_templates
    manifest_templates=$(_manifest_get_names "$manifest_file" "templates")
    if [[ -z "$manifest_templates" ]]; then
        echo "  (none)"
    else
        while IFS= read -r name; do
            [[ -z "$name" ]] && continue
            echo "  - $name"
        done <<< "$manifest_templates"
    fi
}

# ── Internal helpers ──────────────────────────────────────────────────

# Extract pack/template names from manifest.yml list sections.
# Handles both "- name: foo" (object entries) and "- foo" (string entries).
# Usage: _manifest_get_names "$manifest_file" "packs"
_manifest_get_names() {
    local file="$1"
    local section="$2"

    awk -v section="$section" '
        $0 ~ "^"section":" {
            if ($0 ~ /\[\]/) exit
            in_list=1; next
        }
        in_list && /^[^ #]/ { exit }
        in_list && /^  - name:/ {
            sub(/^  - name: */, "")
            gsub(/["\047]/, "")
            gsub(/^ +| +$/, "")
            if ($0 != "") print
        }
        in_list && /^  - [^{]/ && !/^  - name:/ {
            sub(/^  - */, "")
            gsub(/["\047]/, "")
            gsub(/^ +| +$/, "")
            if ($0 != "") print
        }
    ' "$file"
}

# Read per-entry metadata from an existing manifest.yml section.
# Output: lines of "name\tdescription\ttags"
# Usage: _manifest_read_pack_meta "$manifest_file"
_manifest_read_pack_meta() {
    local file="$1"
    awk '
        /^packs:/ { if ($0 ~ /\[\]/) exit; in_list=1; next }
        in_list && /^[^ #]/ { exit }
        in_list && /^  - name:/ {
            if (name != "") print name "\t" desc "\t" tags
            sub(/^  - name: */, ""); gsub(/["\047]/, "")
            name=$0; desc=""; tags=""
        }
        in_list && /^    description:/ {
            sub(/^    description: */, ""); gsub(/["\047]/, "")
            desc=$0
        }
        in_list && /^    tags:/ {
            sub(/^    tags: *\[?/, ""); sub(/\].*$/, ""); gsub(/["\047]/, "")
            tags=$0
        }
        END { if (name != "") print name "\t" desc "\t" tags }
    ' "$file"
}

# Read per-entry metadata from templates section.
_manifest_read_template_meta() {
    local file="$1"
    awk '
        /^templates:/ { if ($0 ~ /\[\]/) exit; in_list=1; next }
        in_list && /^[^ #]/ { exit }
        in_list && /^  - name:/ {
            if (name != "") print name "\t" desc "\t" tags
            sub(/^  - name: */, ""); gsub(/["\047]/, "")
            name=$0; desc=""; tags=""
        }
        in_list && /^    description:/ {
            sub(/^    description: */, ""); gsub(/["\047]/, "")
            desc=$0
        }
        in_list && /^    tags:/ {
            sub(/^    tags: *\[?/, ""); sub(/\].*$/, ""); gsub(/["\047]/, "")
            tags=$0
        }
        END { if (name != "") print name "\t" desc "\t" tags }
    ' "$file"
}

# Look up a field from metadata output.
# Usage: _manifest_lookup_meta "$meta" "pack-name" "description"
_manifest_lookup_meta() {
    local meta="$1"
    local name="$2"
    local field="$3"

    [[ -z "$meta" ]] && return 0

    local line
    line=$(echo "$meta" | awk -F'\t' -v name="$name" '$1 == name { print; exit }')
    [[ -z "$line" ]] && return 0

    case "$field" in
        description) echo "$line" | awk -F'\t' '{ gsub(/^ +| +$/, "", $2); print $2 }' ;;
        tags)        echo "$line" | awk -F'\t' '{ gsub(/^ +| +$/, "", $3); print $3 }' ;;
    esac
}

# ── CLI command ───────────────────────────────────────────────────────

cmd_manifest() {
    local subcmd="${1:-}"
    if [[ -z "$subcmd" || "$subcmd" == "--help" ]]; then
        cat <<'EOF'
Usage: cco manifest <command>

Manage manifest.yml, the index that describes what a Config Repo contains.

Commands:
  refresh    Regenerate manifest.yml from packs/ and templates/ on disk
  validate   Cross-check manifest.yml entries vs actual files on disk
  show       Display manifest.yml contents in a formatted view

Run 'cco manifest <command> --help' for command-specific options.
EOF
        return 0
    fi
    shift

    case "$subcmd" in
        refresh)
            check_global
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    --help)
                        cat <<'EOF'
Usage: cco manifest refresh

Regenerate manifest.yml by scanning packs/ and templates/ directories.
EOF
                        return 0
                        ;;
                    *) die "Unknown option: $1" ;;
                esac
            done
            manifest_refresh "$USER_CONFIG_DIR"
            ok "manifest.yml refreshed"
            ;;
        validate)
            check_global
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    --help)
                        cat <<'EOF'
Usage: cco manifest validate

Cross-check manifest.yml against packs/ and templates/ on disk.
EOF
                        return 0
                        ;;
                    *) die "Unknown option: $1" ;;
                esac
            done
            manifest_validate "$USER_CONFIG_DIR"
            ;;
        show)
            check_global
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    --help)
                        cat <<'EOF'
Usage: cco manifest show

Display manifest.yml contents in a formatted view.
EOF
                        return 0
                        ;;
                    *) die "Unknown option: $1" ;;
                esac
            done
            manifest_show "$USER_CONFIG_DIR"
            ;;
        *)
            die "Unknown manifest command: $subcmd. Run 'cco manifest --help' for usage."
            ;;
    esac
}
