#!/usr/bin/env bash
# lib/share.sh — share.yml lifecycle management
#
# Provides: share_init(), share_refresh(), share_validate(), share_show(),
#           cmd_share()
# Dependencies: colors.sh, utils.sh, yaml.sh
# Globals: USER_CONFIG_DIR, PACKS_DIR, TEMPLATES_DIR

# ── share.yml generation ──────────────────────────────────────────────

# Initialize a minimal share.yml in the given config directory.
# Usage: share_init "$USER_CONFIG_DIR"
share_init() {
    local config_dir="$1"
    local share_file="$config_dir/share.yml"

    if [[ -f "$share_file" ]]; then
        return 0
    fi

    cat > "$share_file" <<'YAML'
# Auto-generated by cco — edit name, description, and tags as needed
name: ""
description: ""

packs: []

templates: []
YAML
}

# Regenerate share.yml by scanning packs/ and templates/ directories.
# Preserves user-edited name, description, and per-entry descriptions/tags.
# Usage: share_refresh "$USER_CONFIG_DIR"
share_refresh() {
    local config_dir="$1"
    local share_file="$config_dir/share.yml"
    local packs_dir="$config_dir/packs"
    local templates_dir="$config_dir/templates"

    # Read existing name/description if share.yml already exists
    local repo_name="" repo_desc=""
    if [[ -f "$share_file" ]]; then
        repo_name=$(yml_get "$share_file" "name")
        repo_desc=$(yml_get "$share_file" "description")
    fi

    # Collect existing per-pack descriptions and tags from current share.yml
    # We store them in associative-style temp files for lookup
    local existing_meta=""
    if [[ -f "$share_file" ]]; then
        existing_meta=$(_share_read_pack_meta "$share_file")
    fi
    local existing_tmpl_meta=""
    if [[ -f "$share_file" ]]; then
        existing_tmpl_meta=$(_share_read_template_meta "$share_file")
    fi

    # Scan packs directory
    local -a pack_entries=()
    if [[ -d "$packs_dir" ]]; then
        for dir in "$packs_dir"/*/; do
            [[ ! -d "$dir" ]] && continue
            local name
            name=$(basename "$dir")
            local pack_yml="$dir/pack.yml"

            # Get description from pack.yml, or from existing share.yml
            local desc=""
            if [[ -f "$pack_yml" ]]; then
                desc=$(yml_get "$pack_yml" "description")
            fi
            if [[ -z "$desc" ]]; then
                desc=$(_share_lookup_meta "$existing_meta" "$name" "description")
            fi

            # Get tags from existing share.yml (not in pack.yml)
            local tags
            tags=$(_share_lookup_meta "$existing_meta" "$name" "tags")

            pack_entries+=("$name|$desc|$tags")
        done
    fi

    # Scan templates directory
    local -a tmpl_entries=()
    if [[ -d "$templates_dir" ]]; then
        for dir in "$templates_dir"/*/; do
            [[ ! -d "$dir" ]] && continue
            local name
            name=$(basename "$dir")

            local desc=""
            desc=$(_share_lookup_meta "$existing_tmpl_meta" "$name" "description")

            local tags
            tags=$(_share_lookup_meta "$existing_tmpl_meta" "$name" "tags")

            tmpl_entries+=("$name|$desc|$tags")
        done
    fi

    # Write share.yml
    {
        echo "# Auto-generated by cco — edit name, description, and tags as needed"
        echo "name: \"${repo_name}\""
        echo "description: \"${repo_desc}\""
        echo ""

        if [[ ${#pack_entries[@]} -eq 0 ]]; then
            echo "packs: []"
        else
            echo "packs:"
            for entry in "${pack_entries[@]}"; do
                IFS='|' read -r name desc tags <<< "$entry"
                echo "  - name: $name"
                if [[ -n "$desc" ]]; then
                    echo "    description: \"$desc\""
                fi
                if [[ -n "$tags" ]]; then
                    echo "    tags: [$tags]"
                fi
            done
        fi

        echo ""

        if [[ ${#tmpl_entries[@]} -eq 0 ]]; then
            echo "templates: []"
        else
            echo "templates:"
            for entry in "${tmpl_entries[@]}"; do
                IFS='|' read -r name desc tags <<< "$entry"
                echo "  - name: $name"
                if [[ -n "$desc" ]]; then
                    echo "    description: \"$desc\""
                fi
                if [[ -n "$tags" ]]; then
                    echo "    tags: [$tags]"
                fi
            done
        fi
    } > "$share_file"
}

# Validate share.yml against disk contents.
# Returns 0 if valid, 1 if issues found.
# Usage: share_validate "$USER_CONFIG_DIR"
share_validate() {
    local config_dir="$1"
    local share_file="$config_dir/share.yml"
    local has_issues=false

    if [[ ! -f "$share_file" ]]; then
        warn "share.yml not found at $share_file"
        return 1
    fi

    # Check packs listed in share.yml exist on disk
    local share_packs
    share_packs=$(_share_get_names "$share_file" "packs")
    while IFS= read -r name; do
        [[ -z "$name" ]] && continue
        if [[ ! -d "$config_dir/packs/$name" ]]; then
            warn "share.yml lists pack '$name' but packs/$name/ does not exist (stale entry)"
            has_issues=true
        fi
    done <<< "$share_packs"

    # Check packs on disk are listed in share.yml
    if [[ -d "$config_dir/packs" ]]; then
        for dir in "$config_dir/packs"/*/; do
            [[ ! -d "$dir" ]] && continue
            local name
            name=$(basename "$dir")
            if ! echo "$share_packs" | grep -qxF "$name"; then
                warn "packs/$name/ exists but is not listed in share.yml (missing entry)"
                has_issues=true
            fi
        done
    fi

    # Check templates listed in share.yml exist on disk
    local share_templates
    share_templates=$(_share_get_names "$share_file" "templates")
    while IFS= read -r name; do
        [[ -z "$name" ]] && continue
        if [[ ! -d "$config_dir/templates/$name" ]]; then
            warn "share.yml lists template '$name' but templates/$name/ does not exist (stale entry)"
            has_issues=true
        fi
    done <<< "$share_templates"

    # Check templates on disk are listed in share.yml
    if [[ -d "$config_dir/templates" ]]; then
        for dir in "$config_dir/templates"/*/; do
            [[ ! -d "$dir" ]] && continue
            local name
            name=$(basename "$dir")
            if ! echo "$share_templates" | grep -qxF "$name"; then
                warn "templates/$name/ exists but is not listed in share.yml (missing entry)"
                has_issues=true
            fi
        done
    fi

    if [[ "$has_issues" == true ]]; then
        info "Run 'cco share refresh' to fix share.yml"
        return 1
    fi

    ok "share.yml is valid"
    return 0
}

# Display share.yml contents in a formatted way.
# Usage: share_show "$USER_CONFIG_DIR"
share_show() {
    local config_dir="$1"
    local share_file="$config_dir/share.yml"

    if [[ ! -f "$share_file" ]]; then
        die "share.yml not found. Run 'cco init' or 'cco share refresh' first."
    fi

    local repo_name repo_desc
    repo_name=$(yml_get "$share_file" "name")
    repo_desc=$(yml_get "$share_file" "description")

    echo -e "${BOLD}Config Repo${NC}"
    if [[ -n "$repo_name" ]]; then
        echo "  Name: $repo_name"
    fi
    if [[ -n "$repo_desc" ]]; then
        echo "  Description: $repo_desc"
    fi
    echo ""

    echo -e "${BOLD}Packs:${NC}"
    local share_packs
    share_packs=$(_share_get_names "$share_file" "packs")
    if [[ -z "$share_packs" ]]; then
        echo "  (none)"
    else
        while IFS= read -r name; do
            [[ -z "$name" ]] && continue
            echo "  - $name"
        done <<< "$share_packs"
    fi
    echo ""

    echo -e "${BOLD}Templates:${NC}"
    local share_templates
    share_templates=$(_share_get_names "$share_file" "templates")
    if [[ -z "$share_templates" ]]; then
        echo "  (none)"
    else
        while IFS= read -r name; do
            [[ -z "$name" ]] && continue
            echo "  - $name"
        done <<< "$share_templates"
    fi
}

# ── Internal helpers ──────────────────────────────────────────────────

# Extract pack/template names from share.yml list sections.
# Handles both "- name: foo" (object entries) and "- foo" (string entries).
# Usage: _share_get_names "$share_file" "packs"
_share_get_names() {
    local file="$1"
    local section="$2"

    awk -v section="$section" '
        $0 ~ "^"section":" {
            if ($0 ~ /\[\]/) exit
            in_list=1; next
        }
        in_list && /^[^ #]/ { exit }
        in_list && /^  - name:/ {
            sub(/^  - name: */, "")
            gsub(/["\047]/, "")
            gsub(/^ +| +$/, "")
            if ($0 != "") print
        }
        in_list && /^  - [^{]/ && !/^  - name:/ {
            sub(/^  - */, "")
            gsub(/["\047]/, "")
            gsub(/^ +| +$/, "")
            if ($0 != "") print
        }
    ' "$file"
}

# Read per-entry metadata from an existing share.yml section.
# Output: lines of "name\tdescription\ttags"
# Usage: _share_read_pack_meta "$share_file"
_share_read_pack_meta() {
    local file="$1"
    awk '
        /^packs:/ { if ($0 ~ /\[\]/) exit; in_list=1; next }
        in_list && /^[^ #]/ { exit }
        in_list && /^  - name:/ {
            if (name != "") print name "\t" desc "\t" tags
            sub(/^  - name: */, ""); gsub(/["\047]/, "")
            name=$0; desc=""; tags=""
        }
        in_list && /^    description:/ {
            sub(/^    description: */, ""); gsub(/["\047]/, "")
            desc=$0
        }
        in_list && /^    tags:/ {
            sub(/^    tags: *\[?/, ""); sub(/\].*$/, ""); gsub(/["\047]/, "")
            tags=$0
        }
        END { if (name != "") print name "\t" desc "\t" tags }
    ' "$file"
}

# Read per-entry metadata from templates section.
_share_read_template_meta() {
    local file="$1"
    awk '
        /^templates:/ { if ($0 ~ /\[\]/) exit; in_list=1; next }
        in_list && /^[^ #]/ { exit }
        in_list && /^  - name:/ {
            if (name != "") print name "\t" desc "\t" tags
            sub(/^  - name: */, ""); gsub(/["\047]/, "")
            name=$0; desc=""; tags=""
        }
        in_list && /^    description:/ {
            sub(/^    description: */, ""); gsub(/["\047]/, "")
            desc=$0
        }
        in_list && /^    tags:/ {
            sub(/^    tags: *\[?/, ""); sub(/\].*$/, ""); gsub(/["\047]/, "")
            tags=$0
        }
        END { if (name != "") print name "\t" desc "\t" tags }
    ' "$file"
}

# Look up a field from metadata output.
# Usage: _share_lookup_meta "$meta" "pack-name" "description"
_share_lookup_meta() {
    local meta="$1"
    local name="$2"
    local field="$3"

    [[ -z "$meta" ]] && return 0

    local line
    line=$(echo "$meta" | awk -F'\t' -v name="$name" '$1 == name { print; exit }')
    [[ -z "$line" ]] && return 0

    case "$field" in
        description) echo "$line" | awk -F'\t' '{ gsub(/^ +| +$/, "", $2); print $2 }' ;;
        tags)        echo "$line" | awk -F'\t' '{ gsub(/^ +| +$/, "", $3); print $3 }' ;;
    esac
}

# ── CLI command ───────────────────────────────────────────────────────

cmd_share() {
    local subcmd="${1:-}"
    [[ -z "$subcmd" ]] && die "Usage: cco share <refresh|validate|show>"
    shift

    case "$subcmd" in
        refresh)
            check_global
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    --help)
                        cat <<'EOF'
Usage: cco share refresh

Regenerate share.yml by scanning packs/ and templates/ directories.
EOF
                        return 0
                        ;;
                    *) die "Unknown option: $1" ;;
                esac
            done
            share_refresh "$USER_CONFIG_DIR"
            ok "share.yml refreshed"
            ;;
        validate)
            check_global
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    --help)
                        cat <<'EOF'
Usage: cco share validate

Cross-check share.yml against packs/ and templates/ on disk.
EOF
                        return 0
                        ;;
                    *) die "Unknown option: $1" ;;
                esac
            done
            share_validate "$USER_CONFIG_DIR"
            ;;
        show)
            check_global
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    --help)
                        cat <<'EOF'
Usage: cco share show

Display share.yml contents in a formatted view.
EOF
                        return 0
                        ;;
                    *) die "Unknown option: $1" ;;
                esac
            done
            share_show "$USER_CONFIG_DIR"
            ;;
        --help)
            cat <<'EOF'
Usage: cco share <command>

Commands:
  refresh    Regenerate share.yml from packs/ and templates/
  validate   Cross-check share.yml vs disk
  show       Display share.yml contents

EOF
            ;;
        *)
            die "Unknown share command: $subcmd. Run 'cco share --help' for usage."
            ;;
    esac
}
