# lib/update-meta.sh — .cco/meta I/O, schema versioning, and migration runner

# ── .cco/meta I/O ────────────────────────────────────────────────────

# Read schema_version from .cco/meta. Returns 0 if file missing.
_read_cco_meta() {
    local meta_file="$1"
    [[ ! -f "$meta_file" ]] && echo "0" && return 0
    awk '/^schema_version:/ {print $2}' "$meta_file"
}

# Read last_seen_changelog from .cco/meta. Returns 0 if file missing or field absent.
_read_last_seen_changelog() {
    local meta_file="$1"
    [[ ! -f "$meta_file" ]] && echo "0" && return 0
    local val
    val=$(awk '/^last_seen_changelog:/ {print $2}' "$meta_file")
    echo "${val:-0}"
}

# Read last_read_changelog from .cco/meta. Returns 0 if file missing or field absent.
_read_last_read_changelog() {
    local meta_file="$1"
    [[ ! -f "$meta_file" ]] && echo "0" && return 0
    local val
    val=$(awk '/^last_read_changelog:/ {print $2}' "$meta_file")
    echo "${val:-0}"
}

# Read manifest entries from .cco/meta. Output: "path\thash" per line.
_read_manifest() {
    local meta_file="$1"
    [[ ! -f "$meta_file" ]] && return 0
    awk '
        /^manifest:/ { in_manifest=1; next }
        /^[a-z]/ { in_manifest=0 }
        in_manifest && /^  [^ ]/ {
            gsub(/^  /, "")
            split($0, parts, ": ")
            printf "%s\t%s\n", parts[1], parts[2]
        }
    ' "$meta_file"
}

# Read languages from .cco/meta. Output: three lines (communication, documentation, code_comments).
_read_languages() {
    local meta_file="$1"
    [[ ! -f "$meta_file" ]] && return 0
    awk '
        /^languages:/ { in_lang=1; next }
        /^[a-z]/ && !/^  / { in_lang=0 }
        in_lang && /communication:/ { gsub(/.*: /, ""); print }
        in_lang && /documentation:/ { gsub(/.*: /, ""); print }
        in_lang && /code_comments:/ { gsub(/.*: /, ""); print }
    ' "$meta_file"
}

# Generate a complete .cco/meta file. Manifest entries read from stdin as "path\thash" lines.
_generate_cco_meta() {
    local meta_file="$1"
    local schema="$2"
    local created="$3"
    local comm_lang="$4"
    local docs_lang="$5"
    local code_lang="$6"
    local last_seen_changelog="${7:-0}"
    local last_read_changelog="${8:-0}"

    {
        printf '# Auto-generated by cco — do not edit\n'
        printf 'schema_version: %d\n' "$schema"
        printf 'created_at: %s\n' "$created"
        printf 'updated_at: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        printf '\nlast_seen_changelog: %d\n' "$last_seen_changelog"
        printf 'last_read_changelog: %d\n' "$last_read_changelog"
        printf '\nlanguages:\n'
        printf '  communication: %s\n' "$comm_lang"
        printf '  documentation: %s\n' "$docs_lang"
        printf '  code_comments: %s\n' "$code_lang"
        printf '\nmanifest:\n'
        while IFS=$'\t' read -r path hash; do
            [[ -z "$path" ]] && continue
            printf '  %s: %s\n' "$path" "$hash"
        done
        # Persist current file policies for transition detection on next update
        printf '\npolicies:\n'
        local _ge _gr _gp
        for _ge in "${GLOBAL_FILE_POLICIES[@]}"; do
            _gr="${_ge%:*}"
            _gp="${_ge##*:}"
            _gr="${_gr#.claude/}"
            printf '  %s: %s\n' "$_gr" "$_gp"
        done
    } > "$meta_file"
}

# Generate a project-scope .cco/meta file. No languages, no changelog.
# Manifest entries read from stdin as "path\thash" lines.
_generate_project_cco_meta() {
    local meta_file="$1"
    local schema="$2"
    local created="$3"
    local template="${4:-base}"

    # Preserve FI-7 fields (local_framework_override, remote_cache) from
    # the existing meta file before overwriting.  These are set by other
    # parts of the update flow (_check_remote_update, --local sync) and
    # must survive meta regeneration.
    local prev_local_override="" prev_rc_commit="" prev_rc_checked=""
    if [[ -f "$meta_file" ]]; then
        prev_local_override=$(yml_get "$meta_file" "local_framework_override" 2>/dev/null) || true
        prev_rc_commit=$(yml_get "$meta_file" "remote_cache.commit" 2>/dev/null) || true
        prev_rc_checked=$(yml_get "$meta_file" "remote_cache.checked" 2>/dev/null) || true
    fi

    {
        printf '# Auto-generated by cco — do not edit\n'
        printf 'schema_version: %d\n' "$schema"
        printf 'created_at: %s\n' "$created"
        printf 'updated_at: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        printf '\ntemplate: %s\n' "$template"
        printf '\nmanifest:\n'
        while IFS=$'\t' read -r path hash; do
            [[ -z "$path" ]] && continue
            printf '  %s: %s\n' "$path" "$hash"
        done
        # Persist current file policies for transition detection on next update
        printf '\npolicies:\n'
        local _pe _pr _pp
        for _pe in "${PROJECT_FILE_POLICIES[@]}"; do
            _pr="${_pe%:*}"
            _pp="${_pe##*:}"
            _pr="${_pr#.claude/}"
            printf '  %s: %s\n' "$_pr" "$_pp"
        done
    } > "$meta_file"

    # Restore preserved FI-7 fields
    if [[ -n "$prev_local_override" ]]; then
        yml_set "$meta_file" "local_framework_override" "$prev_local_override"
    fi
    if [[ -n "$prev_rc_commit" ]]; then
        yml_set "$meta_file" "remote_cache.commit" "$prev_rc_commit"
    fi
    if [[ -n "$prev_rc_checked" ]]; then
        yml_set "$meta_file" "remote_cache.checked" "$prev_rc_checked"
    fi
}

# ── Migration Engine ─────────────────────────────────────────────────

# Scan migrations directory, return the highest MIGRATION_ID found.
_latest_schema_version() {
    local scope="$1"
    local migrations_dir="$REPO_ROOT/migrations/$scope"
    local max_id=0

    [[ ! -d "$migrations_dir" ]] && echo "0" && return 0

    local migration_file
    for migration_file in "$migrations_dir"/*.sh; do
        [[ ! -f "$migration_file" ]] && continue
        local mid
        mid=$(awk '/^MIGRATION_ID=/ {split($0,a,"="); print a[2]}' "$migration_file")
        [[ -n "$mid" && "$mid" -gt "$max_id" ]] && max_id="$mid"
    done

    echo "$max_id"
}

# Run pending migrations for a scope. Returns 0 on success, 1 on failure.
_run_migrations() {
    local scope="$1"
    local target_dir="$2"
    local current_version="$3"
    local meta_file="${4:-}"
    local migrations_dir="$REPO_ROOT/migrations/$scope"
    local ran=0

    [[ ! -d "$migrations_dir" ]] && return 0

    local migration_file
    for migration_file in "$migrations_dir"/*.sh; do
        [[ ! -f "$migration_file" ]] && continue

        # Source in a subshell-safe way: read MIGRATION_ID and MIGRATION_DESC
        local mid mdesc
        mid=$(awk '/^MIGRATION_ID=/ {split($0,a,"="); print a[2]}' "$migration_file")
        mdesc=$(awk -F'"' '/^MIGRATION_DESC=/ {print $2}' "$migration_file")

        [[ -z "$mid" ]] && continue
        [[ "$mid" -le "$current_version" ]] && continue

        info "Running migration $mid: $mdesc"

        # Source the file to get migrate() function, then call it
        local exit_code=0
        (
            # shellcheck source=/dev/null
            source "$migration_file"
            migrate "$target_dir"
        ) || exit_code=$?

        if [[ $exit_code -ne 0 ]]; then
            error "Migration $mid failed (exit code $exit_code)"
            return 1
        fi

        ok "Migration $mid completed"
        ran=$(( ran + 1 ))

        # Update schema_version in meta file if provided
        if [[ -n "$meta_file" && -f "$meta_file" ]]; then
            _sed_i "$meta_file" "^schema_version: .*" "schema_version: $mid"
        fi
    done

    [[ $ran -gt 0 ]] && ok "Ran $ran migration(s)"
    return 0
}

# ── Utility ──────────────────────────────────────────────────────────

# Check if a path is in a bash array (passed as remaining args)
_in_array() {
    local needle="$1"; shift
    local item
    for item in "$@"; do
        [[ "$item" == "$needle" ]] && return 0
    done
    return 1
}
