#!/usr/bin/env bash
# lib/workspace.sh — Workspace YAML generation
#
# Provides: _generate_workspace_yml()
# Dependencies: yaml.sh, utils.sh
# Globals: none

# Generate .claude/workspace.yml for a project (idempotent: preserves descriptions).
# Called by cmd_start after compose generation.
_generate_workspace_yml() {
    local project_dir="$1"
    local project_name="$2"
    local project_yml="$3"
    local pack_names="$4"
    local ws_yml="$project_dir/.claude/workspace.yml"

    {
        echo "# Auto-generated by cco start — descriptions preserved across sessions"
        echo "# Edit descriptions here, or run /init inside the container to populate them"
        echo "project: ${project_name}"
        echo ""
        echo "repos:"
        local repos_output
        repos_output=$(yml_get_repos "$project_yml")
        if [[ -z "$repos_output" ]]; then
            echo "  []"
        else
            while IFS=: read -r repo_path repo_name; do
                [[ -z "$repo_path" ]] && continue
                repo_path=$(expand_path "$repo_path")
                # Preserve existing description from workspace.yml; fall back to
                # project.yml description as seed on first run (if manually set).
                local desc=""
                if [[ -f "$ws_yml" ]]; then
                    desc=$(awk -v name="$repo_name" '
                        /^  - name:/ {
                            sub(/^  - name: */, ""); gsub(/["\047]/, "")
                            current = $0; found = (current == name); next
                        }
                        found && /^    description:/ {
                            sub(/^    description: *"/, ""); sub(/"$/, ""); print; exit
                        }
                        found && /^  - / { found=0 }
                    ' "$ws_yml")
                fi
                # Seed from project.yml if workspace.yml had no description
                if [[ -z "$desc" && -f "$project_yml" ]]; then
                    desc=$(awk -v name="$repo_name" '
                        /^repos:/ { in_repos=1; next }
                        in_repos && /^[^ #]/ { exit }
                        in_repos && /^  - / { in_repo=0 }
                        in_repos && /^    name:/ {
                            sub(/^    name: */, ""); gsub(/["\047]/, "")
                            if ($0 == name) in_repo=1
                        }
                        in_repos && in_repo && /^    description:/ {
                            sub(/^    description: */, ""); gsub(/["\047]/, ""); print; exit
                        }
                    ' "$project_yml")
                fi
                echo "  - name: ${repo_name}"
                echo "    path: /workspace/${repo_name}"
                echo "    description: \"${desc}\""
            done <<< "$repos_output"
        fi
        echo ""
        echo "packs:"
        if [[ -n "$pack_names" ]]; then
            while IFS= read -r pack_name; do
                [[ -z "$pack_name" ]] && continue
                echo "  - ${pack_name}"
            done <<< "$pack_names"
        else
            echo "  []"
        fi

        # Extra mounts (shared libs, read-only assets): list container target paths only
        local extra_mounts_output
        extra_mounts_output=$(yml_get_extra_mounts "$project_yml")
        if [[ -n "$extra_mounts_output" ]]; then
            echo ""
            echo "extra_mounts:"
            while IFS= read -r mount_line; do
                [[ -z "$mount_line" ]] && continue
                # mount_line is source:target[:ro] — extract target (field 2)
                local target
                target=$(echo "$mount_line" | awk -F: '{print $2}')
                local ro_flag
                ro_flag=$(echo "$mount_line" | awk -F: '{print $3}')
                if [[ "$ro_flag" == "ro" ]]; then
                    echo "  - target: ${target}"
                    echo "    readonly: true"
                else
                    echo "  - target: ${target}"
                fi
            done <<< "$extra_mounts_output"
        fi
    } > "$ws_yml"
}
