#!/usr/bin/env bash
# lib/workspace.sh — Workspace YAML generation
#
# Provides: _generate_workspace_yml()
# Dependencies: yaml.sh, utils.sh, local-paths.sh (schema bridge), index.sh
# Globals: none

# Generate workspace.yml for a project (idempotent: preserves descriptions).
# Called by cmd_start before compose generation. arg1 is the overlay `.claude`
# directory (CACHE on a real start, the dump dir under --dry-run --dump): the
# file is a regenerable framework overlay (ADR-0005 F1), never written into the
# committed project `.claude/`.
_generate_workspace_yml() {
    local claude_dir="$1"
    local project_name="$2"
    local project_yml="$3"
    local pack_names="$4"
    local ws_yml="$claude_dir/workspace.yml"

    {
        echo "# Auto-generated by cco start — descriptions preserved across sessions"
        echo "# Edit descriptions here, or run /init inside the container to populate them"
        echo "project: ${project_name}"
        echo ""
        echo "repos:"
        local repos_output
        repos_output=$(_effective_repo_mounts "$project_yml")
        if [[ -z "$repos_output" ]]; then
            echo "  []"
        else
            local repo_name repo_path
            while IFS=$'\t' read -r repo_name repo_path; do
                [[ -z "$repo_name" ]] && continue
                # Preserve existing description from workspace.yml; fall back to
                # project.yml description as seed on first run (if manually set).
                local desc=""
                if [[ -f "$ws_yml" ]]; then
                    desc=$(awk -v name="$repo_name" '
                        /^  - name:/ {
                            sub(/^  - name: */, ""); gsub(/["\047]/, "")
                            current = $0; found = (current == name); next
                        }
                        found && /^    description:/ {
                            sub(/^    description: *"/, ""); sub(/"$/, ""); print; exit
                        }
                        found && /^  - / { found=0 }
                    ' "$ws_yml")
                fi
                # Seed from project.yml if workspace.yml had no description
                if [[ -z "$desc" && -f "$project_yml" ]]; then
                    desc=$(awk -v name="$repo_name" '
                        /^repos:/ { in_repos=1; next }
                        in_repos && /^[^ #]/ { exit }
                        in_repos && /^  - name:/ {
                            sub(/^  - name: */, ""); gsub(/["\047]/, "")
                            in_repo = ($0 == name); next
                        }
                        in_repos && /^  - / { in_repo=0 }
                        in_repos && in_repo && /^    description:/ {
                            sub(/^    description: */, ""); gsub(/["\047]/, ""); print; exit
                        }
                    ' "$project_yml")
                fi
                echo "  - name: ${repo_name}"
                echo "    path: /workspace/${repo_name}"
                echo "    description: \"${desc}\""
            done <<< "$repos_output"
        fi
        echo ""
        echo "packs:"
        if [[ -n "$pack_names" ]]; then
            while IFS= read -r pack_name; do
                [[ -z "$pack_name" ]] && continue
                echo "  - ${pack_name}"
            done <<< "$pack_names"
        else
            echo "  []"
        fi

        # Extra mounts (shared libs, read-only assets): list container target paths only.
        # Bridge emits abs_source<TAB>target<TAB>ro (schema-agnostic).
        local extra_mounts_output
        extra_mounts_output=$(_effective_extra_mounts "$project_yml")
        if [[ -n "$extra_mounts_output" ]]; then
            echo ""
            echo "extra_mounts:"
            local _ws_src _ws_tgt _ws_ro
            while IFS=$'\t' read -r _ws_src _ws_tgt _ws_ro; do
                [[ -z "$_ws_tgt" ]] && continue
                if [[ "$_ws_ro" == "true" ]]; then
                    echo "  - target: ${_ws_tgt}"
                    echo "    readonly: true"
                else
                    echo "  - target: ${_ws_tgt}"
                fi
            done <<< "$extra_mounts_output"
        fi
    } > "$ws_yml"
}
