#!/usr/bin/env bash
# lib/workspace.sh — Workspace YAML generation
#
# Provides: _generate_workspace_yml(), _workspace_collect_knowledge(),
#           _workspace_collect_pathmap()
# Dependencies: yaml.sh, utils.sh, local-paths.sh (schema bridge), index.sh,
#   packs.sh (_pack_resolve_dir), llms.sh (_llms_render_entries)
# Globals: none

# Collect knowledge-file entries for the unified workspace.yml `knowledge`
# section (absorbed from the former packs.md — ADR-0041 R1-D2). Iterates the
# active packs and emits one line per knowledge file: "<container_path>\t<desc>"
# (description may be empty). Folded in from _start_generate_metadata.
_workspace_collect_knowledge() {
    local pack_names="$1"
    local project_dir="$2"

    [[ -z "$pack_names" ]] && return 0
    while IFS= read -r pack_name; do
        [[ -z "$pack_name" ]] && continue
        local _pmroot; _pmroot=$(_pack_resolve_dir "$pack_name" "$project_dir")
        [[ -z "$_pmroot" ]] && continue
        local pack_yml="$_pmroot/pack.yml"
        [[ ! -f "$pack_yml" ]] && continue
        if ! grep -qE '^(name|knowledge|llms|skills|agents|rules):' "$pack_yml"; then
            warn "Pack '$pack_name': pack.yml has no valid top-level keys — check for extra indentation."
            continue
        fi
        local pack_files
        pack_files=$(yml_get_pack_knowledge_files "$pack_yml")
        [[ -z "$pack_files" ]] && continue
        local fname fdesc
        while IFS=$'\t' read -r fname fdesc; do
            [[ -z "$fname" ]] && continue
            printf '%s\t%s\n' "/workspace/.claude/packs/${pack_name}/${fname}" "$fdesc"
        done <<< "$pack_files"
    done <<< "$pack_names"
}

# Collect host->container path-map entries for the gated `path_map` section
# (ADR-0041 R1-D3; emitted only when show_host_paths=on). Labelled pairs so the
# agent never mistakes a host path for a container path. Resolution stays
# host-side, before compose (ADR-0007). Emits "<host>\t<target>\t<readonly>".
_workspace_collect_pathmap() {
    local project_yml="$1"

    local _repo_lines
    _repo_lines=$(_effective_repo_mounts "$project_yml")
    if [[ -n "$_repo_lines" ]]; then
        local _rn _host_p
        while IFS=$'\t' read -r _rn _host_p; do
            [[ -z "$_rn" ]] && continue
            printf '%s\t%s\tfalse\n' "$_host_p" "/workspace/${_rn}"
        done <<< "$_repo_lines"
    fi

    local _extra_mounts
    _extra_mounts=$(_effective_extra_mounts "$project_yml" 2>/dev/null || true)
    if [[ -n "$_extra_mounts" ]]; then
        local _src _tgt _ro
        while IFS=$'\t' read -r _src _tgt _ro; do
            [[ -z "$_src" ]] && continue
            [[ "$_ro" == "true" ]] || _ro="false"
            printf '%s\t%s\t%s\n' "$_src" "$_tgt" "$_ro"
        done <<< "$_extra_mounts"
    fi
}

# Generate workspace.yml for a project (idempotent: preserves descriptions).
# Called by cmd_start before compose generation. arg1 is the overlay `.claude`
# directory (CACHE on a real start, the dump dir under --dry-run --dump): the
# file is a regenerable framework overlay (ADR-0005 F1), never written into the
# committed project `.claude/`.
#
# This is the single agent-facing session-info surface (ADR-0041 R1): it absorbs
# the former packs.md as the `knowledge` + `llms` sections and gains an optional
# `path_map` (emitted only when show_host_paths=on). One generator, one file.
_generate_workspace_yml() {
    local claude_dir="$1"
    local project_name="$2"
    local project_yml="$3"
    local pack_names="$4"
    local project_dir="${5:-}"       # for three-layer pack/llms resolution
    local show_host_paths="${6:-false}"  # gate for the path_map section
    local ws_yml="$claude_dir/workspace.yml"

    # Collect the absorbed sections up front (needed before the redirect block).
    local knowledge_entries llms_entries pathmap_entries=""
    knowledge_entries=$(_workspace_collect_knowledge "$pack_names" "$project_dir")
    llms_entries=$(_llms_render_entries "$project_yml" "$pack_names" "$project_dir")
    if [[ "$show_host_paths" == "true" ]]; then
        pathmap_entries=$(_workspace_collect_pathmap "$project_yml")
    fi

    {
        echo "# Auto-generated by cco start — descriptions preserved across sessions"
        echo "# Edit descriptions here, or run /init inside the container to populate them"
        echo "project: ${project_name}"
        echo ""
        echo "repos:"
        local repos_output
        repos_output=$(_effective_repo_mounts "$project_yml")
        if [[ -z "$repos_output" ]]; then
            echo "  []"
        else
            local repo_name repo_path
            while IFS=$'\t' read -r repo_name repo_path; do
                [[ -z "$repo_name" ]] && continue
                # Preserve existing description from workspace.yml; fall back to
                # project.yml description as seed on first run (if manually set).
                local desc=""
                if [[ -f "$ws_yml" ]]; then
                    desc=$(awk -v name="$repo_name" '
                        /^  - name:/ {
                            sub(/^  - name: */, ""); gsub(/["\047]/, "")
                            current = $0; found = (current == name); next
                        }
                        found && /^    description:/ {
                            sub(/^    description: *"/, ""); sub(/"$/, ""); print; exit
                        }
                        found && /^  - / { found=0 }
                    ' "$ws_yml")
                fi
                # Seed from project.yml if workspace.yml had no description
                if [[ -z "$desc" && -f "$project_yml" ]]; then
                    desc=$(awk -v name="$repo_name" '
                        /^repos:/ { in_repos=1; next }
                        in_repos && /^[^ #]/ { exit }
                        in_repos && /^  - name:/ {
                            sub(/^  - name: */, ""); gsub(/["\047]/, "")
                            in_repo = ($0 == name); next
                        }
                        in_repos && /^  - / { in_repo=0 }
                        in_repos && in_repo && /^    description:/ {
                            sub(/^    description: */, ""); gsub(/["\047]/, ""); print; exit
                        }
                    ' "$project_yml")
                fi
                echo "  - name: ${repo_name}"
                echo "    path: /workspace/${repo_name}"
                echo "    description: \"${desc}\""
            done <<< "$repos_output"
        fi
        echo ""
        echo "packs:"
        if [[ -n "$pack_names" ]]; then
            while IFS= read -r pack_name; do
                [[ -z "$pack_name" ]] && continue
                echo "  - ${pack_name}"
            done <<< "$pack_names"
        else
            echo "  []"
        fi

        # Knowledge files (absorbed from packs.md): read BEFORE implementation.
        # Emitted only when at least one pack contributes a knowledge file; the
        # instructional preamble now lives in the consumers (hooks) — R1-D2.
        if [[ -n "$knowledge_entries" ]]; then
            echo ""
            echo "knowledge:"
            local _kpath _kdesc
            while IFS=$'\t' read -r _kpath _kdesc; do
                [[ -z "$_kpath" ]] && continue
                echo "  - path: ${_kpath}"
                echo "    description: \"${_kdesc}\""
            done <<< "$knowledge_entries"
        fi

        # Official framework docs (llms.txt), absorbed from packs.md.
        if [[ -n "$llms_entries" ]]; then
            echo ""
            echo "llms:"
            local _lpath _ldesc
            while IFS=$'\t' read -r _lpath _ldesc; do
                [[ -z "$_lpath" ]] && continue
                echo "  - path: ${_lpath}"
                echo "    description: \"${_ldesc}\""
            done <<< "$llms_entries"
        fi

        # Extra mounts (shared libs, read-only assets): list container target paths only.
        # Bridge emits abs_source<TAB>target<TAB>ro (schema-agnostic).
        local extra_mounts_output
        extra_mounts_output=$(_effective_extra_mounts "$project_yml")
        if [[ -n "$extra_mounts_output" ]]; then
            echo ""
            echo "extra_mounts:"
            local _ws_src _ws_tgt _ws_ro
            while IFS=$'\t' read -r _ws_src _ws_tgt _ws_ro; do
                [[ -z "$_ws_tgt" ]] && continue
                if [[ "$_ws_ro" == "true" ]]; then
                    echo "  - target: ${_ws_tgt}"
                    echo "    readonly: true"
                else
                    echo "  - target: ${_ws_tgt}"
                fi
            done <<< "$extra_mounts_output"
        fi

        # Host<->container path map (ADR-0041 R1-D3): labelled host->target pairs,
        # emitted only when show_host_paths=on. A read-only runtime view of the
        # user's own machine paths — not committed state (AD3 intact). Lets the
        # agent hand the user copy-pasteable host commands; config-safety.md warns
        # against pasting host paths into commits/PRs.
        if [[ -n "$pathmap_entries" ]]; then
            echo ""
            echo "path_map:"
            local _pm_host _pm_tgt _pm_ro
            while IFS=$'\t' read -r _pm_host _pm_tgt _pm_ro; do
                [[ -z "$_pm_host" ]] && continue
                echo "  - host: ${_pm_host}"
                echo "    target: ${_pm_tgt}"
                echo "    readonly: ${_pm_ro}"
            done <<< "$pathmap_entries"
        fi
    } > "$ws_yml"
}
